// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: orbit.proto

package orbitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbitScience_ListSatellites_FullMethodName     = "/orbit.v1.OrbitScience/ListSatellites"
	OrbitScience_GetTLE_FullMethodName             = "/orbit.v1.OrbitScience/GetTLE"
	OrbitScience_GetCurrentPosition_FullMethodName = "/orbit.v1.OrbitScience/GetCurrentPosition"
	OrbitScience_GetTrack_FullMethodName           = "/orbit.v1.OrbitScience/GetTrack"
	OrbitScience_GetOrbitInfo_FullMethodName       = "/orbit.v1.OrbitScience/GetOrbitInfo"
	OrbitScience_GetSwath_FullMethodName           = "/orbit.v1.OrbitScience/GetSwath"
	OrbitScience_GetPolarCrossings_FullMethodName  = "/orbit.v1.OrbitScience/GetPolarCrossings"
	OrbitScience_GetCoverageHeatmap_FullMethodName = "/orbit.v1.OrbitScience/GetCoverageHeatmap"
	OrbitScience_GetFires_FullMethodName           = "/orbit.v1.OrbitScience/GetFires"
	OrbitScience_SimbadRegion_FullMethodName       = "/orbit.v1.OrbitScience/SimbadRegion"
	OrbitScience_SimbadResolve_FullMethodName      = "/orbit.v1.OrbitScience/SimbadResolve"
	OrbitScience_ListSurveys_FullMethodName        = "/orbit.v1.OrbitScience/ListSurveys"
	OrbitScience_GetCutout_FullMethodName          = "/orbit.v1.OrbitScience/GetCutout"
	OrbitScience_GetCutoutMulti_FullMethodName     = "/orbit.v1.OrbitScience/GetCutoutMulti"
	OrbitScience_GetSitePasses_FullMethodName      = "/orbit.v1.OrbitScience/GetSitePasses"
)

// OrbitScienceClient is the client API for OrbitScience service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrbitScienceClient interface {
	ListSatellites(ctx context.Context, in *ListSatellitesRequest, opts ...grpc.CallOption) (*ListSatellitesResponse, error)
	GetTLE(ctx context.Context, in *GetTLERequest, opts ...grpc.CallOption) (*GetTLEResponse, error)
	GetCurrentPosition(ctx context.Context, in *GetCurrentPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error)
	GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*TrackResponse, error)
	GetOrbitInfo(ctx context.Context, in *GetOrbitInfoRequest, opts ...grpc.CallOption) (*OrbitInfoResponse, error)
	GetSwath(ctx context.Context, in *GetSwathRequest, opts ...grpc.CallOption) (*SwathResponse, error)
	GetPolarCrossings(ctx context.Context, in *GetPolarCrossingsRequest, opts ...grpc.CallOption) (*PolarCrossingsResponse, error)
	GetCoverageHeatmap(ctx context.Context, in *GetCoverageHeatmapRequest, opts ...grpc.CallOption) (*CoverageHeatmapResponse, error)
	GetFires(ctx context.Context, in *GetFiresRequest, opts ...grpc.CallOption) (*GetFiresResponse, error)
	// Astronomy proxies (SIMBAD + HiPS cutouts) — JSON blob for Flask parity
	SimbadRegion(ctx context.Context, in *SimbadRegionRequest, opts ...grpc.CallOption) (*JsonBlob, error)
	SimbadResolve(ctx context.Context, in *SimbadResolveRequest, opts ...grpc.CallOption) (*JsonBlob, error)
	ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*JsonBlob, error)
	GetCutout(ctx context.Context, in *GetCutoutRequest, opts ...grpc.CallOption) (*JsonBlob, error)
	GetCutoutMulti(ctx context.Context, in *GetCutoutMultiRequest, opts ...grpc.CallOption) (*JsonBlob, error)
	GetSitePasses(ctx context.Context, in *GetSitePassesRequest, opts ...grpc.CallOption) (*GetSitePassesResponse, error)
}

type orbitScienceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbitScienceClient(cc grpc.ClientConnInterface) OrbitScienceClient {
	return &orbitScienceClient{cc}
}

func (c *orbitScienceClient) ListSatellites(ctx context.Context, in *ListSatellitesRequest, opts ...grpc.CallOption) (*ListSatellitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSatellitesResponse)
	err := c.cc.Invoke(ctx, OrbitScience_ListSatellites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetTLE(ctx context.Context, in *GetTLERequest, opts ...grpc.CallOption) (*GetTLEResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTLEResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetTLE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetCurrentPosition(ctx context.Context, in *GetCurrentPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetCurrentPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*TrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetOrbitInfo(ctx context.Context, in *GetOrbitInfoRequest, opts ...grpc.CallOption) (*OrbitInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrbitInfoResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetOrbitInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetSwath(ctx context.Context, in *GetSwathRequest, opts ...grpc.CallOption) (*SwathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwathResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetSwath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetPolarCrossings(ctx context.Context, in *GetPolarCrossingsRequest, opts ...grpc.CallOption) (*PolarCrossingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolarCrossingsResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetPolarCrossings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetCoverageHeatmap(ctx context.Context, in *GetCoverageHeatmapRequest, opts ...grpc.CallOption) (*CoverageHeatmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoverageHeatmapResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetCoverageHeatmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetFires(ctx context.Context, in *GetFiresRequest, opts ...grpc.CallOption) (*GetFiresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFiresResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetFires_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) SimbadRegion(ctx context.Context, in *SimbadRegionRequest, opts ...grpc.CallOption) (*JsonBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonBlob)
	err := c.cc.Invoke(ctx, OrbitScience_SimbadRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) SimbadResolve(ctx context.Context, in *SimbadResolveRequest, opts ...grpc.CallOption) (*JsonBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonBlob)
	err := c.cc.Invoke(ctx, OrbitScience_SimbadResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*JsonBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonBlob)
	err := c.cc.Invoke(ctx, OrbitScience_ListSurveys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetCutout(ctx context.Context, in *GetCutoutRequest, opts ...grpc.CallOption) (*JsonBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonBlob)
	err := c.cc.Invoke(ctx, OrbitScience_GetCutout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetCutoutMulti(ctx context.Context, in *GetCutoutMultiRequest, opts ...grpc.CallOption) (*JsonBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonBlob)
	err := c.cc.Invoke(ctx, OrbitScience_GetCutoutMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitScienceClient) GetSitePasses(ctx context.Context, in *GetSitePassesRequest, opts ...grpc.CallOption) (*GetSitePassesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSitePassesResponse)
	err := c.cc.Invoke(ctx, OrbitScience_GetSitePasses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrbitScienceServer is the server API for OrbitScience service.
// All implementations must embed UnimplementedOrbitScienceServer
// for forward compatibility.
type OrbitScienceServer interface {
	ListSatellites(context.Context, *ListSatellitesRequest) (*ListSatellitesResponse, error)
	GetTLE(context.Context, *GetTLERequest) (*GetTLEResponse, error)
	GetCurrentPosition(context.Context, *GetCurrentPositionRequest) (*PositionResponse, error)
	GetTrack(context.Context, *GetTrackRequest) (*TrackResponse, error)
	GetOrbitInfo(context.Context, *GetOrbitInfoRequest) (*OrbitInfoResponse, error)
	GetSwath(context.Context, *GetSwathRequest) (*SwathResponse, error)
	GetPolarCrossings(context.Context, *GetPolarCrossingsRequest) (*PolarCrossingsResponse, error)
	GetCoverageHeatmap(context.Context, *GetCoverageHeatmapRequest) (*CoverageHeatmapResponse, error)
	GetFires(context.Context, *GetFiresRequest) (*GetFiresResponse, error)
	// Astronomy proxies (SIMBAD + HiPS cutouts) — JSON blob for Flask parity
	SimbadRegion(context.Context, *SimbadRegionRequest) (*JsonBlob, error)
	SimbadResolve(context.Context, *SimbadResolveRequest) (*JsonBlob, error)
	ListSurveys(context.Context, *ListSurveysRequest) (*JsonBlob, error)
	GetCutout(context.Context, *GetCutoutRequest) (*JsonBlob, error)
	GetCutoutMulti(context.Context, *GetCutoutMultiRequest) (*JsonBlob, error)
	GetSitePasses(context.Context, *GetSitePassesRequest) (*GetSitePassesResponse, error)
	mustEmbedUnimplementedOrbitScienceServer()
}

// UnimplementedOrbitScienceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbitScienceServer struct{}

func (UnimplementedOrbitScienceServer) ListSatellites(context.Context, *ListSatellitesRequest) (*ListSatellitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSatellites not implemented")
}
func (UnimplementedOrbitScienceServer) GetTLE(context.Context, *GetTLERequest) (*GetTLEResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTLE not implemented")
}
func (UnimplementedOrbitScienceServer) GetCurrentPosition(context.Context, *GetCurrentPositionRequest) (*PositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentPosition not implemented")
}
func (UnimplementedOrbitScienceServer) GetTrack(context.Context, *GetTrackRequest) (*TrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrack not implemented")
}
func (UnimplementedOrbitScienceServer) GetOrbitInfo(context.Context, *GetOrbitInfoRequest) (*OrbitInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrbitInfo not implemented")
}
func (UnimplementedOrbitScienceServer) GetSwath(context.Context, *GetSwathRequest) (*SwathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwath not implemented")
}
func (UnimplementedOrbitScienceServer) GetPolarCrossings(context.Context, *GetPolarCrossingsRequest) (*PolarCrossingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolarCrossings not implemented")
}
func (UnimplementedOrbitScienceServer) GetCoverageHeatmap(context.Context, *GetCoverageHeatmapRequest) (*CoverageHeatmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoverageHeatmap not implemented")
}
func (UnimplementedOrbitScienceServer) GetFires(context.Context, *GetFiresRequest) (*GetFiresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFires not implemented")
}
func (UnimplementedOrbitScienceServer) SimbadRegion(context.Context, *SimbadRegionRequest) (*JsonBlob, error) {
	return nil, status.Error(codes.Unimplemented, "method SimbadRegion not implemented")
}
func (UnimplementedOrbitScienceServer) SimbadResolve(context.Context, *SimbadResolveRequest) (*JsonBlob, error) {
	return nil, status.Error(codes.Unimplemented, "method SimbadResolve not implemented")
}
func (UnimplementedOrbitScienceServer) ListSurveys(context.Context, *ListSurveysRequest) (*JsonBlob, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveys not implemented")
}
func (UnimplementedOrbitScienceServer) GetCutout(context.Context, *GetCutoutRequest) (*JsonBlob, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCutout not implemented")
}
func (UnimplementedOrbitScienceServer) GetCutoutMulti(context.Context, *GetCutoutMultiRequest) (*JsonBlob, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCutoutMulti not implemented")
}
func (UnimplementedOrbitScienceServer) GetSitePasses(context.Context, *GetSitePassesRequest) (*GetSitePassesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSitePasses not implemented")
}
func (UnimplementedOrbitScienceServer) mustEmbedUnimplementedOrbitScienceServer() {}
func (UnimplementedOrbitScienceServer) testEmbeddedByValue()                      {}

// UnsafeOrbitScienceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbitScienceServer will
// result in compilation errors.
type UnsafeOrbitScienceServer interface {
	mustEmbedUnimplementedOrbitScienceServer()
}

func RegisterOrbitScienceServer(s grpc.ServiceRegistrar, srv OrbitScienceServer) {
	// If the following call panics, it indicates UnimplementedOrbitScienceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbitScience_ServiceDesc, srv)
}

func _OrbitScience_ListSatellites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSatellitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).ListSatellites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_ListSatellites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).ListSatellites(ctx, req.(*ListSatellitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetTLE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTLERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetTLE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetTLE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetTLE(ctx, req.(*GetTLERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetCurrentPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetCurrentPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetCurrentPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetCurrentPosition(ctx, req.(*GetCurrentPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetOrbitInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrbitInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetOrbitInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetOrbitInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetOrbitInfo(ctx, req.(*GetOrbitInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetSwath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetSwath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetSwath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetSwath(ctx, req.(*GetSwathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetPolarCrossings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolarCrossingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetPolarCrossings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetPolarCrossings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetPolarCrossings(ctx, req.(*GetPolarCrossingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetCoverageHeatmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoverageHeatmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetCoverageHeatmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetCoverageHeatmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetCoverageHeatmap(ctx, req.(*GetCoverageHeatmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetFires_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFiresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetFires(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetFires_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetFires(ctx, req.(*GetFiresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_SimbadRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimbadRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).SimbadRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_SimbadRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).SimbadRegion(ctx, req.(*SimbadRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_SimbadResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimbadResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).SimbadResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_SimbadResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).SimbadResolve(ctx, req.(*SimbadResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_ListSurveys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).ListSurveys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_ListSurveys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).ListSurveys(ctx, req.(*ListSurveysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetCutout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCutoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetCutout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetCutout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetCutout(ctx, req.(*GetCutoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetCutoutMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCutoutMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetCutoutMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetCutoutMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetCutoutMulti(ctx, req.(*GetCutoutMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitScience_GetSitePasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSitePassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitScienceServer).GetSitePasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitScience_GetSitePasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitScienceServer).GetSitePasses(ctx, req.(*GetSitePassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrbitScience_ServiceDesc is the grpc.ServiceDesc for OrbitScience service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbitScience_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbit.v1.OrbitScience",
	HandlerType: (*OrbitScienceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSatellites",
			Handler:    _OrbitScience_ListSatellites_Handler,
		},
		{
			MethodName: "GetTLE",
			Handler:    _OrbitScience_GetTLE_Handler,
		},
		{
			MethodName: "GetCurrentPosition",
			Handler:    _OrbitScience_GetCurrentPosition_Handler,
		},
		{
			MethodName: "GetTrack",
			Handler:    _OrbitScience_GetTrack_Handler,
		},
		{
			MethodName: "GetOrbitInfo",
			Handler:    _OrbitScience_GetOrbitInfo_Handler,
		},
		{
			MethodName: "GetSwath",
			Handler:    _OrbitScience_GetSwath_Handler,
		},
		{
			MethodName: "GetPolarCrossings",
			Handler:    _OrbitScience_GetPolarCrossings_Handler,
		},
		{
			MethodName: "GetCoverageHeatmap",
			Handler:    _OrbitScience_GetCoverageHeatmap_Handler,
		},
		{
			MethodName: "GetFires",
			Handler:    _OrbitScience_GetFires_Handler,
		},
		{
			MethodName: "SimbadRegion",
			Handler:    _OrbitScience_SimbadRegion_Handler,
		},
		{
			MethodName: "SimbadResolve",
			Handler:    _OrbitScience_SimbadResolve_Handler,
		},
		{
			MethodName: "ListSurveys",
			Handler:    _OrbitScience_ListSurveys_Handler,
		},
		{
			MethodName: "GetCutout",
			Handler:    _OrbitScience_GetCutout_Handler,
		},
		{
			MethodName: "GetCutoutMulti",
			Handler:    _OrbitScience_GetCutoutMulti_Handler,
		},
		{
			MethodName: "GetSitePasses",
			Handler:    _OrbitScience_GetSitePasses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orbit.proto",
}
