// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orbit.proto

package orbitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSatellitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSatellitesRequest) Reset() {
	*x = ListSatellitesRequest{}
	mi := &file_orbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSatellitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSatellitesRequest) ProtoMessage() {}

func (x *ListSatellitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSatellitesRequest.ProtoReflect.Descriptor instead.
func (*ListSatellitesRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{0}
}

type SatelliteMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NoradId       int32                  `protobuf:"varint,3,opt,name=norad_id,json=noradId,proto3" json:"norad_id,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	LaunchYear    int32                  `protobuf:"varint,5,opt,name=launch_year,json=launchYear,proto3" json:"launch_year,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Operator      string                 `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	SwathKm       float32                `protobuf:"fixed32,8,opt,name=swath_km,json=swathKm,proto3" json:"swath_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteMetadata) Reset() {
	*x = SatelliteMetadata{}
	mi := &file_orbit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteMetadata) ProtoMessage() {}

func (x *SatelliteMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteMetadata.ProtoReflect.Descriptor instead.
func (*SatelliteMetadata) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{1}
}

func (x *SatelliteMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SatelliteMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SatelliteMetadata) GetNoradId() int32 {
	if x != nil {
		return x.NoradId
	}
	return 0
}

func (x *SatelliteMetadata) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SatelliteMetadata) GetLaunchYear() int32 {
	if x != nil {
		return x.LaunchYear
	}
	return 0
}

func (x *SatelliteMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SatelliteMetadata) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SatelliteMetadata) GetSwathKm() float32 {
	if x != nil {
		return x.SwathKm
	}
	return 0
}

type ListSatellitesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Satellites       []*SatelliteMetadata   `protobuf:"bytes,1,rep,name=satellites,proto3" json:"satellites,omitempty"`
	DefaultSatellite string                 `protobuf:"bytes,2,opt,name=default_satellite,json=defaultSatellite,proto3" json:"default_satellite,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSatellitesResponse) Reset() {
	*x = ListSatellitesResponse{}
	mi := &file_orbit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSatellitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSatellitesResponse) ProtoMessage() {}

func (x *ListSatellitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSatellitesResponse.ProtoReflect.Descriptor instead.
func (*ListSatellitesResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{2}
}

func (x *ListSatellitesResponse) GetSatellites() []*SatelliteMetadata {
	if x != nil {
		return x.Satellites
	}
	return nil
}

func (x *ListSatellitesResponse) GetDefaultSatellite() string {
	if x != nil {
		return x.DefaultSatellite
	}
	return ""
}

type GetTLERequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"` // e.g., "noaa21"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLERequest) Reset() {
	*x = GetTLERequest{}
	mi := &file_orbit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLERequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLERequest) ProtoMessage() {}

func (x *GetTLERequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLERequest.ProtoReflect.Descriptor instead.
func (*GetTLERequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{3}
}

func (x *GetTLERequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

type OrbitalParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InclinationDeg float64                `protobuf:"fixed64,1,opt,name=inclination_deg,json=inclinationDeg,proto3" json:"inclination_deg,omitempty"`
	RaanDeg        float64                `protobuf:"fixed64,2,opt,name=raan_deg,json=raanDeg,proto3" json:"raan_deg,omitempty"`
	Eccentricity   float64                `protobuf:"fixed64,3,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	ArgPerigeeDeg  float64                `protobuf:"fixed64,4,opt,name=arg_perigee_deg,json=argPerigeeDeg,proto3" json:"arg_perigee_deg,omitempty"`
	MeanAnomalyDeg float64                `protobuf:"fixed64,5,opt,name=mean_anomaly_deg,json=meanAnomalyDeg,proto3" json:"mean_anomaly_deg,omitempty"`
	MeanMotion     float64                `protobuf:"fixed64,6,opt,name=mean_motion,json=meanMotion,proto3" json:"mean_motion,omitempty"`
	OrbitNumber    int32                  `protobuf:"varint,7,opt,name=orbit_number,json=orbitNumber,proto3" json:"orbit_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrbitalParams) Reset() {
	*x = OrbitalParams{}
	mi := &file_orbit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitalParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitalParams) ProtoMessage() {}

func (x *OrbitalParams) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitalParams.ProtoReflect.Descriptor instead.
func (*OrbitalParams) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{4}
}

func (x *OrbitalParams) GetInclinationDeg() float64 {
	if x != nil {
		return x.InclinationDeg
	}
	return 0
}

func (x *OrbitalParams) GetRaanDeg() float64 {
	if x != nil {
		return x.RaanDeg
	}
	return 0
}

func (x *OrbitalParams) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *OrbitalParams) GetArgPerigeeDeg() float64 {
	if x != nil {
		return x.ArgPerigeeDeg
	}
	return 0
}

func (x *OrbitalParams) GetMeanAnomalyDeg() float64 {
	if x != nil {
		return x.MeanAnomalyDeg
	}
	return 0
}

func (x *OrbitalParams) GetMeanMotion() float64 {
	if x != nil {
		return x.MeanMotion
	}
	return 0
}

func (x *OrbitalParams) GetOrbitNumber() int32 {
	if x != nil {
		return x.OrbitNumber
	}
	return 0
}

type GetTLEResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteKey  string                 `protobuf:"bytes,1,opt,name=satellite_key,json=satelliteKey,proto3" json:"satellite_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NoradId       int32                  `protobuf:"varint,3,opt,name=norad_id,json=noradId,proto3" json:"norad_id,omitempty"`
	TleLine1      string                 `protobuf:"bytes,4,opt,name=tle_line1,json=tleLine1,proto3" json:"tle_line1,omitempty"`
	TleLine2      string                 `protobuf:"bytes,5,opt,name=tle_line2,json=tleLine2,proto3" json:"tle_line2,omitempty"`
	Epoch         string                 `protobuf:"bytes,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AgeHours      float64                `protobuf:"fixed64,7,opt,name=age_hours,json=ageHours,proto3" json:"age_hours,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	OrbitalParams *OrbitalParams         `protobuf:"bytes,9,opt,name=orbital_params,json=orbitalParams,proto3" json:"orbital_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTLEResponse) Reset() {
	*x = GetTLEResponse{}
	mi := &file_orbit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTLEResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTLEResponse) ProtoMessage() {}

func (x *GetTLEResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTLEResponse.ProtoReflect.Descriptor instead.
func (*GetTLEResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{5}
}

func (x *GetTLEResponse) GetSatelliteKey() string {
	if x != nil {
		return x.SatelliteKey
	}
	return ""
}

func (x *GetTLEResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTLEResponse) GetNoradId() int32 {
	if x != nil {
		return x.NoradId
	}
	return 0
}

func (x *GetTLEResponse) GetTleLine1() string {
	if x != nil {
		return x.TleLine1
	}
	return ""
}

func (x *GetTLEResponse) GetTleLine2() string {
	if x != nil {
		return x.TleLine2
	}
	return ""
}

func (x *GetTLEResponse) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *GetTLEResponse) GetAgeHours() float64 {
	if x != nil {
		return x.AgeHours
	}
	return 0
}

func (x *GetTLEResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetTLEResponse) GetOrbitalParams() *OrbitalParams {
	if x != nil {
		return x.OrbitalParams
	}
	return nil
}

type GetCurrentPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	At            *string                `protobuf:"bytes,2,opt,name=at,proto3,oneof" json:"at,omitempty"` // ISO8601 string or empty for current time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPositionRequest) Reset() {
	*x = GetCurrentPositionRequest{}
	mi := &file_orbit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPositionRequest) ProtoMessage() {}

func (x *GetCurrentPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPositionRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPositionRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentPositionRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetCurrentPositionRequest) GetAt() string {
	if x != nil && x.At != nil {
		return *x.At
	}
	return ""
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeKm    float64                `protobuf:"fixed64,3,opt,name=altitude_km,json=altitudeKm,proto3" json:"altitude_km,omitempty"`
	VelocityKmS   float64                `protobuf:"fixed64,4,opt,name=velocity_km_s,json=velocityKmS,proto3" json:"velocity_km_s,omitempty"`
	OrbitNumber   int32                  `protobuf:"varint,5,opt,name=orbit_number,json=orbitNumber,proto3" json:"orbit_number,omitempty"`
	SatelliteKey  string                 `protobuf:"bytes,6,opt,name=satellite_key,json=satelliteKey,proto3" json:"satellite_key,omitempty"`
	SatelliteName string                 `protobuf:"bytes,7,opt,name=satellite_name,json=satelliteName,proto3" json:"satellite_name,omitempty"`
	Color         string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Timestamp     string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_orbit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{7}
}

func (x *PositionResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionResponse) GetAltitudeKm() float64 {
	if x != nil {
		return x.AltitudeKm
	}
	return 0
}

func (x *PositionResponse) GetVelocityKmS() float64 {
	if x != nil {
		return x.VelocityKmS
	}
	return 0
}

func (x *PositionResponse) GetOrbitNumber() int32 {
	if x != nil {
		return x.OrbitNumber
	}
	return 0
}

func (x *PositionResponse) GetSatelliteKey() string {
	if x != nil {
		return x.SatelliteKey
	}
	return ""
}

func (x *PositionResponse) GetSatelliteName() string {
	if x != nil {
		return x.SatelliteName
	}
	return ""
}

func (x *PositionResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PositionResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetTrackRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Satellite       string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	Start           string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"` // ISO8601
	End             string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`     // ISO8601
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	StepSeconds     int32                  `protobuf:"varint,5,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTrackRequest) Reset() {
	*x = GetTrackRequest{}
	mi := &file_orbit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackRequest) ProtoMessage() {}

func (x *GetTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackRequest.ProtoReflect.Descriptor instead.
func (*GetTrackRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrackRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetTrackRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetTrackRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetTrackRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *GetTrackRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

type TrackPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPosition) Reset() {
	*x = TrackPosition{}
	mi := &file_orbit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPosition) ProtoMessage() {}

func (x *TrackPosition) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPosition.ProtoReflect.Descriptor instead.
func (*TrackPosition) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{9}
}

func (x *TrackPosition) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TrackPosition) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TrackPosition) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *TrackPosition) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*TrackPosition       `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	StepSeconds   int32                  `protobuf:"varint,2,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	TotalPoints   int32                  `protobuf:"varint,3,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	Start         string                 `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_orbit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{10}
}

func (x *TrackResponse) GetPositions() []*TrackPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *TrackResponse) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *TrackResponse) GetTotalPoints() int32 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *TrackResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TrackResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type GetOrbitInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrbitInfoRequest) Reset() {
	*x = GetOrbitInfoRequest{}
	mi := &file_orbit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrbitInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrbitInfoRequest) ProtoMessage() {}

func (x *GetOrbitInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrbitInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOrbitInfoRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrbitInfoRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

type OrbitInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InclinationDeg     float64                `protobuf:"fixed64,1,opt,name=inclination_deg,json=inclinationDeg,proto3" json:"inclination_deg,omitempty"`
	Eccentricity       float64                `protobuf:"fixed64,2,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	MeanMotionRevDay   float64                `protobuf:"fixed64,3,opt,name=mean_motion_rev_day,json=meanMotionRevDay,proto3" json:"mean_motion_rev_day,omitempty"`
	PeriodMinutes      float64                `protobuf:"fixed64,4,opt,name=period_minutes,json=periodMinutes,proto3" json:"period_minutes,omitempty"`
	AltitudeKm         float64                `protobuf:"fixed64,5,opt,name=altitude_km,json=altitudeKm,proto3" json:"altitude_km,omitempty"`
	TleEpoch           string                 `protobuf:"bytes,6,opt,name=tle_epoch,json=tleEpoch,proto3" json:"tle_epoch,omitempty"`
	TleAgeHours        float64                `protobuf:"fixed64,7,opt,name=tle_age_hours,json=tleAgeHours,proto3" json:"tle_age_hours,omitempty"`
	CurrentOrbitNumber int32                  `protobuf:"varint,8,opt,name=current_orbit_number,json=currentOrbitNumber,proto3" json:"current_orbit_number,omitempty"`
	SatelliteKey       string                 `protobuf:"bytes,9,opt,name=satellite_key,json=satelliteKey,proto3" json:"satellite_key,omitempty"`
	SatelliteName      string                 `protobuf:"bytes,10,opt,name=satellite_name,json=satelliteName,proto3" json:"satellite_name,omitempty"`
	Color              string                 `protobuf:"bytes,11,opt,name=color,proto3" json:"color,omitempty"`
	SwathKm            float64                `protobuf:"fixed64,12,opt,name=swath_km,json=swathKm,proto3" json:"swath_km,omitempty"`
	TleSource          string                 `protobuf:"bytes,13,opt,name=tle_source,json=tleSource,proto3" json:"tle_source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrbitInfoResponse) Reset() {
	*x = OrbitInfoResponse{}
	mi := &file_orbit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitInfoResponse) ProtoMessage() {}

func (x *OrbitInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitInfoResponse.ProtoReflect.Descriptor instead.
func (*OrbitInfoResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{12}
}

func (x *OrbitInfoResponse) GetInclinationDeg() float64 {
	if x != nil {
		return x.InclinationDeg
	}
	return 0
}

func (x *OrbitInfoResponse) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *OrbitInfoResponse) GetMeanMotionRevDay() float64 {
	if x != nil {
		return x.MeanMotionRevDay
	}
	return 0
}

func (x *OrbitInfoResponse) GetPeriodMinutes() float64 {
	if x != nil {
		return x.PeriodMinutes
	}
	return 0
}

func (x *OrbitInfoResponse) GetAltitudeKm() float64 {
	if x != nil {
		return x.AltitudeKm
	}
	return 0
}

func (x *OrbitInfoResponse) GetTleEpoch() string {
	if x != nil {
		return x.TleEpoch
	}
	return ""
}

func (x *OrbitInfoResponse) GetTleAgeHours() float64 {
	if x != nil {
		return x.TleAgeHours
	}
	return 0
}

func (x *OrbitInfoResponse) GetCurrentOrbitNumber() int32 {
	if x != nil {
		return x.CurrentOrbitNumber
	}
	return 0
}

func (x *OrbitInfoResponse) GetSatelliteKey() string {
	if x != nil {
		return x.SatelliteKey
	}
	return ""
}

func (x *OrbitInfoResponse) GetSatelliteName() string {
	if x != nil {
		return x.SatelliteName
	}
	return ""
}

func (x *OrbitInfoResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *OrbitInfoResponse) GetSwathKm() float64 {
	if x != nil {
		return x.SwathKm
	}
	return 0
}

func (x *OrbitInfoResponse) GetTleSource() string {
	if x != nil {
		return x.TleSource
	}
	return ""
}

type GetSwathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwathRequest) Reset() {
	*x = GetSwathRequest{}
	mi := &file_orbit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwathRequest) ProtoMessage() {}

func (x *GetSwathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwathRequest.ProtoReflect.Descriptor instead.
func (*GetSwathRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{13}
}

func (x *GetSwathRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetSwathRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_orbit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{14}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type SwathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Point                 `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Polygon       []*Point               `protobuf:"bytes,3,rep,name=polygon,proto3" json:"polygon,omitempty"` // using Point instead of array array to fit protobuf cleanly, Go edge maps it to frontend JSON
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwathResponse) Reset() {
	*x = SwathResponse{}
	mi := &file_orbit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwathResponse) ProtoMessage() {}

func (x *SwathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwathResponse.ProtoReflect.Descriptor instead.
func (*SwathResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{15}
}

func (x *SwathResponse) GetCenter() *Point {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *SwathResponse) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *SwathResponse) GetPolygon() []*Point {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *SwathResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetPolarCrossingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolarCrossingsRequest) Reset() {
	*x = GetPolarCrossingsRequest{}
	mi := &file_orbit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolarCrossingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolarCrossingsRequest) ProtoMessage() {}

func (x *GetPolarCrossingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolarCrossingsRequest.ProtoReflect.Descriptor instead.
func (*GetPolarCrossingsRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{16}
}

func (x *GetPolarCrossingsRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetPolarCrossingsRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type Crossing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crossing) Reset() {
	*x = Crossing{}
	mi := &file_orbit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crossing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crossing) ProtoMessage() {}

func (x *Crossing) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crossing.ProtoReflect.Descriptor instead.
func (*Crossing) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{17}
}

func (x *Crossing) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Crossing) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PolarCrossingsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AscendingNodes  []*Crossing            `protobuf:"bytes,1,rep,name=ascending_nodes,json=ascendingNodes,proto3" json:"ascending_nodes,omitempty"`
	DescendingNodes []*Crossing            `protobuf:"bytes,2,rep,name=descending_nodes,json=descendingNodes,proto3" json:"descending_nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolarCrossingsResponse) Reset() {
	*x = PolarCrossingsResponse{}
	mi := &file_orbit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolarCrossingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarCrossingsResponse) ProtoMessage() {}

func (x *PolarCrossingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarCrossingsResponse.ProtoReflect.Descriptor instead.
func (*PolarCrossingsResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{18}
}

func (x *PolarCrossingsResponse) GetAscendingNodes() []*Crossing {
	if x != nil {
		return x.AscendingNodes
	}
	return nil
}

func (x *PolarCrossingsResponse) GetDescendingNodes() []*Crossing {
	if x != nil {
		return x.DescendingNodes
	}
	return nil
}

type GetCoverageHeatmapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	GridSize      int32                  `protobuf:"varint,3,opt,name=grid_size,json=gridSize,proto3" json:"grid_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoverageHeatmapRequest) Reset() {
	*x = GetCoverageHeatmapRequest{}
	mi := &file_orbit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoverageHeatmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoverageHeatmapRequest) ProtoMessage() {}

func (x *GetCoverageHeatmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoverageHeatmapRequest.ProtoReflect.Descriptor instead.
func (*GetCoverageHeatmapRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{19}
}

func (x *GetCoverageHeatmapRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetCoverageHeatmapRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *GetCoverageHeatmapRequest) GetGridSize() int32 {
	if x != nil {
		return x.GridSize
	}
	return 0
}

type HeatmapCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Passes        int32                  `protobuf:"varint,3,opt,name=passes,proto3" json:"passes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapCell) Reset() {
	*x = HeatmapCell{}
	mi := &file_orbit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapCell) ProtoMessage() {}

func (x *HeatmapCell) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapCell.ProtoReflect.Descriptor instead.
func (*HeatmapCell) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{20}
}

func (x *HeatmapCell) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *HeatmapCell) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *HeatmapCell) GetPasses() int32 {
	if x != nil {
		return x.Passes
	}
	return 0
}

type CoverageHeatmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GridSize      int32                  `protobuf:"varint,1,opt,name=grid_size,json=gridSize,proto3" json:"grid_size,omitempty"`
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	Satellite     string                 `protobuf:"bytes,3,opt,name=satellite,proto3" json:"satellite,omitempty"`
	SwathKm       float64                `protobuf:"fixed64,4,opt,name=swath_km,json=swathKm,proto3" json:"swath_km,omitempty"`
	MaxPasses     int32                  `protobuf:"varint,5,opt,name=max_passes,json=maxPasses,proto3" json:"max_passes,omitempty"`
	CellCount     int32                  `protobuf:"varint,6,opt,name=cell_count,json=cellCount,proto3" json:"cell_count,omitempty"`
	Cells         []*HeatmapCell         `protobuf:"bytes,7,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverageHeatmapResponse) Reset() {
	*x = CoverageHeatmapResponse{}
	mi := &file_orbit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageHeatmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageHeatmapResponse) ProtoMessage() {}

func (x *CoverageHeatmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageHeatmapResponse.ProtoReflect.Descriptor instead.
func (*CoverageHeatmapResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{21}
}

func (x *CoverageHeatmapResponse) GetGridSize() int32 {
	if x != nil {
		return x.GridSize
	}
	return 0
}

func (x *CoverageHeatmapResponse) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *CoverageHeatmapResponse) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *CoverageHeatmapResponse) GetSwathKm() float64 {
	if x != nil {
		return x.SwathKm
	}
	return 0
}

func (x *CoverageHeatmapResponse) GetMaxPasses() int32 {
	if x != nil {
		return x.MaxPasses
	}
	return 0
}

func (x *CoverageHeatmapResponse) GetCellCount() int32 {
	if x != nil {
		return x.CellCount
	}
	return 0
}

func (x *CoverageHeatmapResponse) GetCells() []*HeatmapCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type GetFiresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellite     string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"` // catalog key; maps to VIIRS_*_NRT source
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`        // 24 or 48 (maps to 1- or 2-day FIRMS world dump)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiresRequest) Reset() {
	*x = GetFiresRequest{}
	mi := &file_orbit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiresRequest) ProtoMessage() {}

func (x *GetFiresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiresRequest.ProtoReflect.Descriptor instead.
func (*GetFiresRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{22}
}

func (x *GetFiresRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetFiresRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type FirePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Brightness    float64                `protobuf:"fixed64,3,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Confidence    string                 `protobuf:"bytes,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // "nominal" | "high" (low filtered out)
	Frp           float64                `protobuf:"fixed64,5,opt,name=frp,proto3" json:"frp,omitempty"`
	AcqDate       string                 `protobuf:"bytes,6,opt,name=acq_date,json=acqDate,proto3" json:"acq_date,omitempty"`
	AcqTime       string                 `protobuf:"bytes,7,opt,name=acq_time,json=acqTime,proto3" json:"acq_time,omitempty"`
	Daynight      string                 `protobuf:"bytes,8,opt,name=daynight,proto3" json:"daynight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirePoint) Reset() {
	*x = FirePoint{}
	mi := &file_orbit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirePoint) ProtoMessage() {}

func (x *FirePoint) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirePoint.ProtoReflect.Descriptor instead.
func (*FirePoint) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{23}
}

func (x *FirePoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FirePoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *FirePoint) GetBrightness() float64 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *FirePoint) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *FirePoint) GetFrp() float64 {
	if x != nil {
		return x.Frp
	}
	return 0
}

func (x *FirePoint) GetAcqDate() string {
	if x != nil {
		return x.AcqDate
	}
	return ""
}

func (x *FirePoint) GetAcqTime() string {
	if x != nil {
		return x.AcqTime
	}
	return ""
}

func (x *FirePoint) GetDaynight() string {
	if x != nil {
		return x.Daynight
	}
	return ""
}

type GetFiresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fires         []*FirePoint           `protobuf:"bytes,1,rep,name=fires,proto3" json:"fires,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	DayRange      int32                  `protobuf:"varint,4,opt,name=day_range,json=dayRange,proto3" json:"day_range,omitempty"`
	Cached        bool                   `protobuf:"varint,5,opt,name=cached,proto3" json:"cached,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // non-empty when upstream/parse failed; fires may be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiresResponse) Reset() {
	*x = GetFiresResponse{}
	mi := &file_orbit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiresResponse) ProtoMessage() {}

func (x *GetFiresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiresResponse.ProtoReflect.Descriptor instead.
func (*GetFiresResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{24}
}

func (x *GetFiresResponse) GetFires() []*FirePoint {
	if x != nil {
		return x.Fires
	}
	return nil
}

func (x *GetFiresResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetFiresResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetFiresResponse) GetDayRange() int32 {
	if x != nil {
		return x.DayRange
	}
	return 0
}

func (x *GetFiresResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *GetFiresResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Generic Flask-compatible JSON body (SIMBAD / cutouts have nested shapes).
type JsonBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonBlob) Reset() {
	*x = JsonBlob{}
	mi := &file_orbit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonBlob) ProtoMessage() {}

func (x *JsonBlob) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonBlob.ProtoReflect.Descriptor instead.
func (*JsonBlob) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{25}
}

func (x *JsonBlob) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *JsonBlob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JsonBlob) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type SimbadRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ra            float64                `protobuf:"fixed64,1,opt,name=ra,proto3" json:"ra,omitempty"`
	Dec           float64                `protobuf:"fixed64,2,opt,name=dec,proto3" json:"dec,omitempty"`
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"` // degrees, default 1.0
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`    // default 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimbadRegionRequest) Reset() {
	*x = SimbadRegionRequest{}
	mi := &file_orbit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimbadRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimbadRegionRequest) ProtoMessage() {}

func (x *SimbadRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimbadRegionRequest.ProtoReflect.Descriptor instead.
func (*SimbadRegionRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{26}
}

func (x *SimbadRegionRequest) GetRa() float64 {
	if x != nil {
		return x.Ra
	}
	return 0
}

func (x *SimbadRegionRequest) GetDec() float64 {
	if x != nil {
		return x.Dec
	}
	return 0
}

func (x *SimbadRegionRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SimbadRegionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SimbadResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimbadResolveRequest) Reset() {
	*x = SimbadResolveRequest{}
	mi := &file_orbit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimbadResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimbadResolveRequest) ProtoMessage() {}

func (x *SimbadResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimbadResolveRequest.ProtoReflect.Descriptor instead.
func (*SimbadResolveRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{27}
}

func (x *SimbadResolveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSurveysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveysRequest) Reset() {
	*x = ListSurveysRequest{}
	mi := &file_orbit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveysRequest) ProtoMessage() {}

func (x *ListSurveysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveysRequest.ProtoReflect.Descriptor instead.
func (*ListSurveysRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{28}
}

type GetCutoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ra            float64                `protobuf:"fixed64,1,opt,name=ra,proto3" json:"ra,omitempty"`
	Dec           float64                `protobuf:"fixed64,2,opt,name=dec,proto3" json:"dec,omitempty"`
	Fov           float64                `protobuf:"fixed64,3,opt,name=fov,proto3" json:"fov,omitempty"`
	Survey        string                 `protobuf:"bytes,4,opt,name=survey,proto3" json:"survey,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCutoutRequest) Reset() {
	*x = GetCutoutRequest{}
	mi := &file_orbit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCutoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCutoutRequest) ProtoMessage() {}

func (x *GetCutoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCutoutRequest.ProtoReflect.Descriptor instead.
func (*GetCutoutRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{29}
}

func (x *GetCutoutRequest) GetRa() float64 {
	if x != nil {
		return x.Ra
	}
	return 0
}

func (x *GetCutoutRequest) GetDec() float64 {
	if x != nil {
		return x.Dec
	}
	return 0
}

func (x *GetCutoutRequest) GetFov() float64 {
	if x != nil {
		return x.Fov
	}
	return 0
}

func (x *GetCutoutRequest) GetSurvey() string {
	if x != nil {
		return x.Survey
	}
	return ""
}

func (x *GetCutoutRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetCutoutRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetCutoutRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetCutoutMultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ra            float64                `protobuf:"fixed64,1,opt,name=ra,proto3" json:"ra,omitempty"`
	Dec           float64                `protobuf:"fixed64,2,opt,name=dec,proto3" json:"dec,omitempty"`
	Fov           float64                `protobuf:"fixed64,3,opt,name=fov,proto3" json:"fov,omitempty"`
	Surveys       string                 `protobuf:"bytes,4,opt,name=surveys,proto3" json:"surveys,omitempty"` // comma-separated keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCutoutMultiRequest) Reset() {
	*x = GetCutoutMultiRequest{}
	mi := &file_orbit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCutoutMultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCutoutMultiRequest) ProtoMessage() {}

func (x *GetCutoutMultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCutoutMultiRequest.ProtoReflect.Descriptor instead.
func (*GetCutoutMultiRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{30}
}

func (x *GetCutoutMultiRequest) GetRa() float64 {
	if x != nil {
		return x.Ra
	}
	return 0
}

func (x *GetCutoutMultiRequest) GetDec() float64 {
	if x != nil {
		return x.Dec
	}
	return 0
}

func (x *GetCutoutMultiRequest) GetFov() float64 {
	if x != nil {
		return x.Fov
	}
	return 0
}

func (x *GetCutoutMultiRequest) GetSurveys() string {
	if x != nil {
		return x.Surveys
	}
	return ""
}

// Ground-site pass prediction
type GetSitePassesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Satellite       string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	Lat             float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon             float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	SiteAltKm       float64                `protobuf:"fixed64,4,opt,name=site_alt_km,json=siteAltKm,proto3" json:"site_alt_km,omitempty"`
	Hours           float64                `protobuf:"fixed64,5,opt,name=hours,proto3" json:"hours,omitempty"`                                              // look-ahead window (default 24)
	MinElevationDeg float64                `protobuf:"fixed64,6,opt,name=min_elevation_deg,json=minElevationDeg,proto3" json:"min_elevation_deg,omitempty"` // AOS/LOS threshold (default 10)
	StepSeconds     int32                  `protobuf:"varint,7,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`                // sample step (default 30)
	Start           *string                `protobuf:"bytes,8,opt,name=start,proto3,oneof" json:"start,omitempty"`                                          // ISO8601 UTC; empty = now
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSitePassesRequest) Reset() {
	*x = GetSitePassesRequest{}
	mi := &file_orbit_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSitePassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSitePassesRequest) ProtoMessage() {}

func (x *GetSitePassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSitePassesRequest.ProtoReflect.Descriptor instead.
func (*GetSitePassesRequest) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{31}
}

func (x *GetSitePassesRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetSitePassesRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetSitePassesRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GetSitePassesRequest) GetSiteAltKm() float64 {
	if x != nil {
		return x.SiteAltKm
	}
	return 0
}

func (x *GetSitePassesRequest) GetHours() float64 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *GetSitePassesRequest) GetMinElevationDeg() float64 {
	if x != nil {
		return x.MinElevationDeg
	}
	return 0
}

func (x *GetSitePassesRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *GetSitePassesRequest) GetStart() string {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return ""
}

type SitePass struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Aos                     string                 `protobuf:"bytes,1,opt,name=aos,proto3" json:"aos,omitempty"`
	Los                     string                 `protobuf:"bytes,2,opt,name=los,proto3" json:"los,omitempty"`
	MaxElevation            float64                `protobuf:"fixed64,3,opt,name=max_elevation,json=maxElevation,proto3" json:"max_elevation,omitempty"`
	MaxElevationTime        string                 `protobuf:"bytes,4,opt,name=max_elevation_time,json=maxElevationTime,proto3" json:"max_elevation_time,omitempty"`
	DurationSeconds         int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DurationMinutes         float64                `protobuf:"fixed64,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	SatSunlitAtMax          *bool                  `protobuf:"varint,7,opt,name=sat_sunlit_at_max,json=satSunlitAtMax,proto3,oneof" json:"sat_sunlit_at_max,omitempty"`
	SiteDaylightAtMax       bool                   `protobuf:"varint,8,opt,name=site_daylight_at_max,json=siteDaylightAtMax,proto3" json:"site_daylight_at_max,omitempty"`
	SiteSolarElevationAtMax float64                `protobuf:"fixed64,9,opt,name=site_solar_elevation_at_max,json=siteSolarElevationAtMax,proto3" json:"site_solar_elevation_at_max,omitempty"`
	VisualPassCandidate     bool                   `protobuf:"varint,10,opt,name=visual_pass_candidate,json=visualPassCandidate,proto3" json:"visual_pass_candidate,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SitePass) Reset() {
	*x = SitePass{}
	mi := &file_orbit_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SitePass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SitePass) ProtoMessage() {}

func (x *SitePass) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SitePass.ProtoReflect.Descriptor instead.
func (*SitePass) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{32}
}

func (x *SitePass) GetAos() string {
	if x != nil {
		return x.Aos
	}
	return ""
}

func (x *SitePass) GetLos() string {
	if x != nil {
		return x.Los
	}
	return ""
}

func (x *SitePass) GetMaxElevation() float64 {
	if x != nil {
		return x.MaxElevation
	}
	return 0
}

func (x *SitePass) GetMaxElevationTime() string {
	if x != nil {
		return x.MaxElevationTime
	}
	return ""
}

func (x *SitePass) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SitePass) GetDurationMinutes() float64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *SitePass) GetSatSunlitAtMax() bool {
	if x != nil && x.SatSunlitAtMax != nil {
		return *x.SatSunlitAtMax
	}
	return false
}

func (x *SitePass) GetSiteDaylightAtMax() bool {
	if x != nil {
		return x.SiteDaylightAtMax
	}
	return false
}

func (x *SitePass) GetSiteSolarElevationAtMax() float64 {
	if x != nil {
		return x.SiteSolarElevationAtMax
	}
	return 0
}

func (x *SitePass) GetVisualPassCandidate() bool {
	if x != nil {
		return x.VisualPassCandidate
	}
	return false
}

type GetSitePassesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Satellite       string                 `protobuf:"bytes,1,opt,name=satellite,proto3" json:"satellite,omitempty"`
	Lat             float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon             float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	MinElevationDeg float64                `protobuf:"fixed64,4,opt,name=min_elevation_deg,json=minElevationDeg,proto3" json:"min_elevation_deg,omitempty"`
	WindowStart     string                 `protobuf:"bytes,5,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd       string                 `protobuf:"bytes,6,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	Passes          []*SitePass            `protobuf:"bytes,7,rep,name=passes,proto3" json:"passes,omitempty"`
	Count           int32                  `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSitePassesResponse) Reset() {
	*x = GetSitePassesResponse{}
	mi := &file_orbit_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSitePassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSitePassesResponse) ProtoMessage() {}

func (x *GetSitePassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSitePassesResponse.ProtoReflect.Descriptor instead.
func (*GetSitePassesResponse) Descriptor() ([]byte, []int) {
	return file_orbit_proto_rawDescGZIP(), []int{33}
}

func (x *GetSitePassesResponse) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *GetSitePassesResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetSitePassesResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GetSitePassesResponse) GetMinElevationDeg() float64 {
	if x != nil {
		return x.MinElevationDeg
	}
	return 0
}

func (x *GetSitePassesResponse) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *GetSitePassesResponse) GetWindowEnd() string {
	if x != nil {
		return x.WindowEnd
	}
	return ""
}

func (x *GetSitePassesResponse) GetPasses() []*SitePass {
	if x != nil {
		return x.Passes
	}
	return nil
}

func (x *GetSitePassesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_orbit_proto protoreflect.FileDescriptor

const file_orbit_proto_rawDesc = "" +
	"\n" +
	"\vorbit.proto\x12\borbit.v1\"\x17\n" +
	"\x15ListSatellitesRequest\"\xde\x01\n" +
	"\x11SatelliteMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bnorad_id\x18\x03 \x01(\x05R\anoradId\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1f\n" +
	"\vlaunch_year\x18\x05 \x01(\x05R\n" +
	"launchYear\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x12\x19\n" +
	"\bswath_km\x18\b \x01(\x02R\aswathKm\"\x82\x01\n" +
	"\x16ListSatellitesResponse\x12;\n" +
	"\n" +
	"satellites\x18\x01 \x03(\v2\x1b.orbit.v1.SatelliteMetadataR\n" +
	"satellites\x12+\n" +
	"\x11default_satellite\x18\x02 \x01(\tR\x10defaultSatellite\"-\n" +
	"\rGetTLERequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\"\x8d\x02\n" +
	"\rOrbitalParams\x12'\n" +
	"\x0finclination_deg\x18\x01 \x01(\x01R\x0einclinationDeg\x12\x19\n" +
	"\braan_deg\x18\x02 \x01(\x01R\araanDeg\x12\"\n" +
	"\feccentricity\x18\x03 \x01(\x01R\feccentricity\x12&\n" +
	"\x0farg_perigee_deg\x18\x04 \x01(\x01R\rargPerigeeDeg\x12(\n" +
	"\x10mean_anomaly_deg\x18\x05 \x01(\x01R\x0emeanAnomalyDeg\x12\x1f\n" +
	"\vmean_motion\x18\x06 \x01(\x01R\n" +
	"meanMotion\x12!\n" +
	"\forbit_number\x18\a \x01(\x05R\vorbitNumber\"\xa9\x02\n" +
	"\x0eGetTLEResponse\x12#\n" +
	"\rsatellite_key\x18\x01 \x01(\tR\fsatelliteKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bnorad_id\x18\x03 \x01(\x05R\anoradId\x12\x1b\n" +
	"\ttle_line1\x18\x04 \x01(\tR\btleLine1\x12\x1b\n" +
	"\ttle_line2\x18\x05 \x01(\tR\btleLine2\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\tR\x05epoch\x12\x1b\n" +
	"\tage_hours\x18\a \x01(\x01R\bageHours\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12>\n" +
	"\x0eorbital_params\x18\t \x01(\v2\x17.orbit.v1.OrbitalParamsR\rorbitalParams\"U\n" +
	"\x19GetCurrentPositionRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x13\n" +
	"\x02at\x18\x02 \x01(\tH\x00R\x02at\x88\x01\x01B\x05\n" +
	"\x03_at\"\xb4\x02\n" +
	"\x10PositionResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\valtitude_km\x18\x03 \x01(\x01R\n" +
	"altitudeKm\x12\"\n" +
	"\rvelocity_km_s\x18\x04 \x01(\x01R\vvelocityKmS\x12!\n" +
	"\forbit_number\x18\x05 \x01(\x05R\vorbitNumber\x12#\n" +
	"\rsatellite_key\x18\x06 \x01(\tR\fsatelliteKey\x12%\n" +
	"\x0esatellite_name\x18\a \x01(\tR\rsatelliteName\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"\xa5\x01\n" +
	"\x0fGetTrackRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12!\n" +
	"\fstep_seconds\x18\x05 \x01(\x05R\vstepSeconds\"Y\n" +
	"\rTrackPosition\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x01R\x03alt\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\"\xb4\x01\n" +
	"\rTrackResponse\x125\n" +
	"\tpositions\x18\x01 \x03(\v2\x17.orbit.v1.TrackPositionR\tpositions\x12!\n" +
	"\fstep_seconds\x18\x02 \x01(\x05R\vstepSeconds\x12!\n" +
	"\ftotal_points\x18\x03 \x01(\x05R\vtotalPoints\x12\x14\n" +
	"\x05start\x18\x04 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x05 \x01(\tR\x03end\"3\n" +
	"\x13GetOrbitInfoRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\"\xe6\x03\n" +
	"\x11OrbitInfoResponse\x12'\n" +
	"\x0finclination_deg\x18\x01 \x01(\x01R\x0einclinationDeg\x12\"\n" +
	"\feccentricity\x18\x02 \x01(\x01R\feccentricity\x12-\n" +
	"\x13mean_motion_rev_day\x18\x03 \x01(\x01R\x10meanMotionRevDay\x12%\n" +
	"\x0eperiod_minutes\x18\x04 \x01(\x01R\rperiodMinutes\x12\x1f\n" +
	"\valtitude_km\x18\x05 \x01(\x01R\n" +
	"altitudeKm\x12\x1b\n" +
	"\ttle_epoch\x18\x06 \x01(\tR\btleEpoch\x12\"\n" +
	"\rtle_age_hours\x18\a \x01(\x01R\vtleAgeHours\x120\n" +
	"\x14current_orbit_number\x18\b \x01(\x05R\x12currentOrbitNumber\x12#\n" +
	"\rsatellite_key\x18\t \x01(\tR\fsatelliteKey\x12%\n" +
	"\x0esatellite_name\x18\n" +
	" \x01(\tR\rsatelliteName\x12\x14\n" +
	"\x05color\x18\v \x01(\tR\x05color\x12\x19\n" +
	"\bswath_km\x18\f \x01(\x01R\aswathKm\x12\x1d\n" +
	"\n" +
	"tle_source\x18\r \x01(\tR\ttleSource\"L\n" +
	"\x0fGetSwathRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\"+\n" +
	"\x05Point\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\x9e\x01\n" +
	"\rSwathResponse\x12'\n" +
	"\x06center\x18\x01 \x01(\v2\x0f.orbit.v1.PointR\x06center\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\x12)\n" +
	"\apolygon\x18\x03 \x03(\v2\x0f.orbit.v1.PointR\apolygon\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"N\n" +
	"\x18GetPolarCrossingsRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\"<\n" +
	"\bCrossing\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x94\x01\n" +
	"\x16PolarCrossingsResponse\x12;\n" +
	"\x0fascending_nodes\x18\x01 \x03(\v2\x12.orbit.v1.CrossingR\x0eascendingNodes\x12=\n" +
	"\x10descending_nodes\x18\x02 \x03(\v2\x12.orbit.v1.CrossingR\x0fdescendingNodes\"l\n" +
	"\x19GetCoverageHeatmapRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\x12\x1b\n" +
	"\tgrid_size\x18\x03 \x01(\x05R\bgridSize\"I\n" +
	"\vHeatmapCell\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06passes\x18\x03 \x01(\x05R\x06passes\"\xf0\x01\n" +
	"\x17CoverageHeatmapResponse\x12\x1b\n" +
	"\tgrid_size\x18\x01 \x01(\x05R\bgridSize\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\x12\x1c\n" +
	"\tsatellite\x18\x03 \x01(\tR\tsatellite\x12\x19\n" +
	"\bswath_km\x18\x04 \x01(\x01R\aswathKm\x12\x1d\n" +
	"\n" +
	"max_passes\x18\x05 \x01(\x05R\tmaxPasses\x12\x1d\n" +
	"\n" +
	"cell_count\x18\x06 \x01(\x05R\tcellCount\x12+\n" +
	"\x05cells\x18\a \x03(\v2\x15.orbit.v1.HeatmapCellR\x05cells\"E\n" +
	"\x0fGetFiresRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\"\xd3\x01\n" +
	"\tFirePoint\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x1e\n" +
	"\n" +
	"brightness\x18\x03 \x01(\x01R\n" +
	"brightness\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\tR\n" +
	"confidence\x12\x10\n" +
	"\x03frp\x18\x05 \x01(\x01R\x03frp\x12\x19\n" +
	"\bacq_date\x18\x06 \x01(\tR\aacqDate\x12\x19\n" +
	"\bacq_time\x18\a \x01(\tR\aacqTime\x12\x1a\n" +
	"\bdaynight\x18\b \x01(\tR\bdaynight\"\xb6\x01\n" +
	"\x10GetFiresResponse\x12)\n" +
	"\x05fires\x18\x01 \x03(\v2\x13.orbit.v1.FirePointR\x05fires\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1b\n" +
	"\tday_range\x18\x04 \x01(\x05R\bdayRange\x12\x16\n" +
	"\x06cached\x18\x05 \x01(\bR\x06cached\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"U\n" +
	"\bJsonBlob\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"e\n" +
	"\x13SimbadRegionRequest\x12\x0e\n" +
	"\x02ra\x18\x01 \x01(\x01R\x02ra\x12\x10\n" +
	"\x03dec\x18\x02 \x01(\x01R\x03dec\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"*\n" +
	"\x14SimbadResolveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12ListSurveysRequest\"\xa4\x01\n" +
	"\x10GetCutoutRequest\x12\x0e\n" +
	"\x02ra\x18\x01 \x01(\x01R\x02ra\x12\x10\n" +
	"\x03dec\x18\x02 \x01(\x01R\x03dec\x12\x10\n" +
	"\x03fov\x18\x03 \x01(\x01R\x03fov\x12\x16\n" +
	"\x06survey\x18\x04 \x01(\tR\x06survey\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\"e\n" +
	"\x15GetCutoutMultiRequest\x12\x0e\n" +
	"\x02ra\x18\x01 \x01(\x01R\x02ra\x12\x10\n" +
	"\x03dec\x18\x02 \x01(\x01R\x03dec\x12\x10\n" +
	"\x03fov\x18\x03 \x01(\x01R\x03fov\x12\x18\n" +
	"\asurveys\x18\x04 \x01(\tR\asurveys\"\x82\x02\n" +
	"\x14GetSitePassesRequest\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x1e\n" +
	"\vsite_alt_km\x18\x04 \x01(\x01R\tsiteAltKm\x12\x14\n" +
	"\x05hours\x18\x05 \x01(\x01R\x05hours\x12*\n" +
	"\x11min_elevation_deg\x18\x06 \x01(\x01R\x0fminElevationDeg\x12!\n" +
	"\fstep_seconds\x18\a \x01(\x05R\vstepSeconds\x12\x19\n" +
	"\x05start\x18\b \x01(\tH\x00R\x05start\x88\x01\x01B\b\n" +
	"\x06_start\"\xc0\x03\n" +
	"\bSitePass\x12\x10\n" +
	"\x03aos\x18\x01 \x01(\tR\x03aos\x12\x10\n" +
	"\x03los\x18\x02 \x01(\tR\x03los\x12#\n" +
	"\rmax_elevation\x18\x03 \x01(\x01R\fmaxElevation\x12,\n" +
	"\x12max_elevation_time\x18\x04 \x01(\tR\x10maxElevationTime\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x01R\x0fdurationMinutes\x12.\n" +
	"\x11sat_sunlit_at_max\x18\a \x01(\bH\x00R\x0esatSunlitAtMax\x88\x01\x01\x12/\n" +
	"\x14site_daylight_at_max\x18\b \x01(\bR\x11siteDaylightAtMax\x12<\n" +
	"\x1bsite_solar_elevation_at_max\x18\t \x01(\x01R\x17siteSolarElevationAtMax\x122\n" +
	"\x15visual_pass_candidate\x18\n" +
	" \x01(\bR\x13visualPassCandidateB\x14\n" +
	"\x12_sat_sunlit_at_max\"\x89\x02\n" +
	"\x15GetSitePassesResponse\x12\x1c\n" +
	"\tsatellite\x18\x01 \x01(\tR\tsatellite\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12*\n" +
	"\x11min_elevation_deg\x18\x04 \x01(\x01R\x0fminElevationDeg\x12!\n" +
	"\fwindow_start\x18\x05 \x01(\tR\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x06 \x01(\tR\twindowEnd\x12*\n" +
	"\x06passes\x18\a \x03(\v2\x12.orbit.v1.SitePassR\x06passes\x12\x14\n" +
	"\x05count\x18\b \x01(\x05R\x05count2\xde\b\n" +
	"\fOrbitScience\x12S\n" +
	"\x0eListSatellites\x12\x1f.orbit.v1.ListSatellitesRequest\x1a .orbit.v1.ListSatellitesResponse\x12;\n" +
	"\x06GetTLE\x12\x17.orbit.v1.GetTLERequest\x1a\x18.orbit.v1.GetTLEResponse\x12U\n" +
	"\x12GetCurrentPosition\x12#.orbit.v1.GetCurrentPositionRequest\x1a\x1a.orbit.v1.PositionResponse\x12>\n" +
	"\bGetTrack\x12\x19.orbit.v1.GetTrackRequest\x1a\x17.orbit.v1.TrackResponse\x12J\n" +
	"\fGetOrbitInfo\x12\x1d.orbit.v1.GetOrbitInfoRequest\x1a\x1b.orbit.v1.OrbitInfoResponse\x12>\n" +
	"\bGetSwath\x12\x19.orbit.v1.GetSwathRequest\x1a\x17.orbit.v1.SwathResponse\x12Y\n" +
	"\x11GetPolarCrossings\x12\".orbit.v1.GetPolarCrossingsRequest\x1a .orbit.v1.PolarCrossingsResponse\x12\\\n" +
	"\x12GetCoverageHeatmap\x12#.orbit.v1.GetCoverageHeatmapRequest\x1a!.orbit.v1.CoverageHeatmapResponse\x12A\n" +
	"\bGetFires\x12\x19.orbit.v1.GetFiresRequest\x1a\x1a.orbit.v1.GetFiresResponse\x12A\n" +
	"\fSimbadRegion\x12\x1d.orbit.v1.SimbadRegionRequest\x1a\x12.orbit.v1.JsonBlob\x12C\n" +
	"\rSimbadResolve\x12\x1e.orbit.v1.SimbadResolveRequest\x1a\x12.orbit.v1.JsonBlob\x12?\n" +
	"\vListSurveys\x12\x1c.orbit.v1.ListSurveysRequest\x1a\x12.orbit.v1.JsonBlob\x12;\n" +
	"\tGetCutout\x12\x1a.orbit.v1.GetCutoutRequest\x1a\x12.orbit.v1.JsonBlob\x12E\n" +
	"\x0eGetCutoutMulti\x12\x1f.orbit.v1.GetCutoutMultiRequest\x1a\x12.orbit.v1.JsonBlob\x12P\n" +
	"\rGetSitePasses\x12\x1e.orbit.v1.GetSitePassesRequest\x1a\x1f.orbit.v1.GetSitePassesResponseB)Z'noaa21_orbit/api/proto/orbit/v1;orbitv1b\x06proto3"

var (
	file_orbit_proto_rawDescOnce sync.Once
	file_orbit_proto_rawDescData []byte
)

func file_orbit_proto_rawDescGZIP() []byte {
	file_orbit_proto_rawDescOnce.Do(func() {
		file_orbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbit_proto_rawDesc), len(file_orbit_proto_rawDesc)))
	})
	return file_orbit_proto_rawDescData
}

var file_orbit_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_orbit_proto_goTypes = []any{
	(*ListSatellitesRequest)(nil),     // 0: orbit.v1.ListSatellitesRequest
	(*SatelliteMetadata)(nil),         // 1: orbit.v1.SatelliteMetadata
	(*ListSatellitesResponse)(nil),    // 2: orbit.v1.ListSatellitesResponse
	(*GetTLERequest)(nil),             // 3: orbit.v1.GetTLERequest
	(*OrbitalParams)(nil),             // 4: orbit.v1.OrbitalParams
	(*GetTLEResponse)(nil),            // 5: orbit.v1.GetTLEResponse
	(*GetCurrentPositionRequest)(nil), // 6: orbit.v1.GetCurrentPositionRequest
	(*PositionResponse)(nil),          // 7: orbit.v1.PositionResponse
	(*GetTrackRequest)(nil),           // 8: orbit.v1.GetTrackRequest
	(*TrackPosition)(nil),             // 9: orbit.v1.TrackPosition
	(*TrackResponse)(nil),             // 10: orbit.v1.TrackResponse
	(*GetOrbitInfoRequest)(nil),       // 11: orbit.v1.GetOrbitInfoRequest
	(*OrbitInfoResponse)(nil),         // 12: orbit.v1.OrbitInfoResponse
	(*GetSwathRequest)(nil),           // 13: orbit.v1.GetSwathRequest
	(*Point)(nil),                     // 14: orbit.v1.Point
	(*SwathResponse)(nil),             // 15: orbit.v1.SwathResponse
	(*GetPolarCrossingsRequest)(nil),  // 16: orbit.v1.GetPolarCrossingsRequest
	(*Crossing)(nil),                  // 17: orbit.v1.Crossing
	(*PolarCrossingsResponse)(nil),    // 18: orbit.v1.PolarCrossingsResponse
	(*GetCoverageHeatmapRequest)(nil), // 19: orbit.v1.GetCoverageHeatmapRequest
	(*HeatmapCell)(nil),               // 20: orbit.v1.HeatmapCell
	(*CoverageHeatmapResponse)(nil),   // 21: orbit.v1.CoverageHeatmapResponse
	(*GetFiresRequest)(nil),           // 22: orbit.v1.GetFiresRequest
	(*FirePoint)(nil),                 // 23: orbit.v1.FirePoint
	(*GetFiresResponse)(nil),          // 24: orbit.v1.GetFiresResponse
	(*JsonBlob)(nil),                  // 25: orbit.v1.JsonBlob
	(*SimbadRegionRequest)(nil),       // 26: orbit.v1.SimbadRegionRequest
	(*SimbadResolveRequest)(nil),      // 27: orbit.v1.SimbadResolveRequest
	(*ListSurveysRequest)(nil),        // 28: orbit.v1.ListSurveysRequest
	(*GetCutoutRequest)(nil),          // 29: orbit.v1.GetCutoutRequest
	(*GetCutoutMultiRequest)(nil),     // 30: orbit.v1.GetCutoutMultiRequest
	(*GetSitePassesRequest)(nil),      // 31: orbit.v1.GetSitePassesRequest
	(*SitePass)(nil),                  // 32: orbit.v1.SitePass
	(*GetSitePassesResponse)(nil),     // 33: orbit.v1.GetSitePassesResponse
}
var file_orbit_proto_depIdxs = []int32{
	1,  // 0: orbit.v1.ListSatellitesResponse.satellites:type_name -> orbit.v1.SatelliteMetadata
	4,  // 1: orbit.v1.GetTLEResponse.orbital_params:type_name -> orbit.v1.OrbitalParams
	9,  // 2: orbit.v1.TrackResponse.positions:type_name -> orbit.v1.TrackPosition
	14, // 3: orbit.v1.SwathResponse.center:type_name -> orbit.v1.Point
	14, // 4: orbit.v1.SwathResponse.polygon:type_name -> orbit.v1.Point
	17, // 5: orbit.v1.PolarCrossingsResponse.ascending_nodes:type_name -> orbit.v1.Crossing
	17, // 6: orbit.v1.PolarCrossingsResponse.descending_nodes:type_name -> orbit.v1.Crossing
	20, // 7: orbit.v1.CoverageHeatmapResponse.cells:type_name -> orbit.v1.HeatmapCell
	23, // 8: orbit.v1.GetFiresResponse.fires:type_name -> orbit.v1.FirePoint
	32, // 9: orbit.v1.GetSitePassesResponse.passes:type_name -> orbit.v1.SitePass
	0,  // 10: orbit.v1.OrbitScience.ListSatellites:input_type -> orbit.v1.ListSatellitesRequest
	3,  // 11: orbit.v1.OrbitScience.GetTLE:input_type -> orbit.v1.GetTLERequest
	6,  // 12: orbit.v1.OrbitScience.GetCurrentPosition:input_type -> orbit.v1.GetCurrentPositionRequest
	8,  // 13: orbit.v1.OrbitScience.GetTrack:input_type -> orbit.v1.GetTrackRequest
	11, // 14: orbit.v1.OrbitScience.GetOrbitInfo:input_type -> orbit.v1.GetOrbitInfoRequest
	13, // 15: orbit.v1.OrbitScience.GetSwath:input_type -> orbit.v1.GetSwathRequest
	16, // 16: orbit.v1.OrbitScience.GetPolarCrossings:input_type -> orbit.v1.GetPolarCrossingsRequest
	19, // 17: orbit.v1.OrbitScience.GetCoverageHeatmap:input_type -> orbit.v1.GetCoverageHeatmapRequest
	22, // 18: orbit.v1.OrbitScience.GetFires:input_type -> orbit.v1.GetFiresRequest
	26, // 19: orbit.v1.OrbitScience.SimbadRegion:input_type -> orbit.v1.SimbadRegionRequest
	27, // 20: orbit.v1.OrbitScience.SimbadResolve:input_type -> orbit.v1.SimbadResolveRequest
	28, // 21: orbit.v1.OrbitScience.ListSurveys:input_type -> orbit.v1.ListSurveysRequest
	29, // 22: orbit.v1.OrbitScience.GetCutout:input_type -> orbit.v1.GetCutoutRequest
	30, // 23: orbit.v1.OrbitScience.GetCutoutMulti:input_type -> orbit.v1.GetCutoutMultiRequest
	31, // 24: orbit.v1.OrbitScience.GetSitePasses:input_type -> orbit.v1.GetSitePassesRequest
	2,  // 25: orbit.v1.OrbitScience.ListSatellites:output_type -> orbit.v1.ListSatellitesResponse
	5,  // 26: orbit.v1.OrbitScience.GetTLE:output_type -> orbit.v1.GetTLEResponse
	7,  // 27: orbit.v1.OrbitScience.GetCurrentPosition:output_type -> orbit.v1.PositionResponse
	10, // 28: orbit.v1.OrbitScience.GetTrack:output_type -> orbit.v1.TrackResponse
	12, // 29: orbit.v1.OrbitScience.GetOrbitInfo:output_type -> orbit.v1.OrbitInfoResponse
	15, // 30: orbit.v1.OrbitScience.GetSwath:output_type -> orbit.v1.SwathResponse
	18, // 31: orbit.v1.OrbitScience.GetPolarCrossings:output_type -> orbit.v1.PolarCrossingsResponse
	21, // 32: orbit.v1.OrbitScience.GetCoverageHeatmap:output_type -> orbit.v1.CoverageHeatmapResponse
	24, // 33: orbit.v1.OrbitScience.GetFires:output_type -> orbit.v1.GetFiresResponse
	25, // 34: orbit.v1.OrbitScience.SimbadRegion:output_type -> orbit.v1.JsonBlob
	25, // 35: orbit.v1.OrbitScience.SimbadResolve:output_type -> orbit.v1.JsonBlob
	25, // 36: orbit.v1.OrbitScience.ListSurveys:output_type -> orbit.v1.JsonBlob
	25, // 37: orbit.v1.OrbitScience.GetCutout:output_type -> orbit.v1.JsonBlob
	25, // 38: orbit.v1.OrbitScience.GetCutoutMulti:output_type -> orbit.v1.JsonBlob
	33, // 39: orbit.v1.OrbitScience.GetSitePasses:output_type -> orbit.v1.GetSitePassesResponse
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_orbit_proto_init() }
func file_orbit_proto_init() {
	if File_orbit_proto != nil {
		return
	}
	file_orbit_proto_msgTypes[6].OneofWrappers = []any{}
	file_orbit_proto_msgTypes[31].OneofWrappers = []any{}
	file_orbit_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbit_proto_rawDesc), len(file_orbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orbit_proto_goTypes,
		DependencyIndexes: file_orbit_proto_depIdxs,
		MessageInfos:      file_orbit_proto_msgTypes,
	}.Build()
	File_orbit_proto = out.File
	file_orbit_proto_goTypes = nil
	file_orbit_proto_depIdxs = nil
}
