# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from backend.orbit_science import orbit_pb2 as orbit__pb2
except ImportError:
    import orbit_pb2 as orbit__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orbit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrbitScienceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSatellites = channel.unary_unary(
                '/orbit.v1.OrbitScience/ListSatellites',
                request_serializer=orbit__pb2.ListSatellitesRequest.SerializeToString,
                response_deserializer=orbit__pb2.ListSatellitesResponse.FromString,
                _registered_method=True)
        self.GetTLE = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetTLE',
                request_serializer=orbit__pb2.GetTLERequest.SerializeToString,
                response_deserializer=orbit__pb2.GetTLEResponse.FromString,
                _registered_method=True)
        self.GetCurrentPosition = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetCurrentPosition',
                request_serializer=orbit__pb2.GetCurrentPositionRequest.SerializeToString,
                response_deserializer=orbit__pb2.PositionResponse.FromString,
                _registered_method=True)
        self.GetTrack = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetTrack',
                request_serializer=orbit__pb2.GetTrackRequest.SerializeToString,
                response_deserializer=orbit__pb2.TrackResponse.FromString,
                _registered_method=True)
        self.GetOrbitInfo = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetOrbitInfo',
                request_serializer=orbit__pb2.GetOrbitInfoRequest.SerializeToString,
                response_deserializer=orbit__pb2.OrbitInfoResponse.FromString,
                _registered_method=True)
        self.GetSwath = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetSwath',
                request_serializer=orbit__pb2.GetSwathRequest.SerializeToString,
                response_deserializer=orbit__pb2.SwathResponse.FromString,
                _registered_method=True)
        self.GetPolarCrossings = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetPolarCrossings',
                request_serializer=orbit__pb2.GetPolarCrossingsRequest.SerializeToString,
                response_deserializer=orbit__pb2.PolarCrossingsResponse.FromString,
                _registered_method=True)
        self.GetCoverageHeatmap = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetCoverageHeatmap',
                request_serializer=orbit__pb2.GetCoverageHeatmapRequest.SerializeToString,
                response_deserializer=orbit__pb2.CoverageHeatmapResponse.FromString,
                _registered_method=True)
        self.GetFires = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetFires',
                request_serializer=orbit__pb2.GetFiresRequest.SerializeToString,
                response_deserializer=orbit__pb2.GetFiresResponse.FromString,
                _registered_method=True)
        self.SimbadRegion = channel.unary_unary(
                '/orbit.v1.OrbitScience/SimbadRegion',
                request_serializer=orbit__pb2.SimbadRegionRequest.SerializeToString,
                response_deserializer=orbit__pb2.JsonBlob.FromString,
                _registered_method=True)
        self.SimbadResolve = channel.unary_unary(
                '/orbit.v1.OrbitScience/SimbadResolve',
                request_serializer=orbit__pb2.SimbadResolveRequest.SerializeToString,
                response_deserializer=orbit__pb2.JsonBlob.FromString,
                _registered_method=True)
        self.ListSurveys = channel.unary_unary(
                '/orbit.v1.OrbitScience/ListSurveys',
                request_serializer=orbit__pb2.ListSurveysRequest.SerializeToString,
                response_deserializer=orbit__pb2.JsonBlob.FromString,
                _registered_method=True)
        self.GetCutout = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetCutout',
                request_serializer=orbit__pb2.GetCutoutRequest.SerializeToString,
                response_deserializer=orbit__pb2.JsonBlob.FromString,
                _registered_method=True)
        self.GetCutoutMulti = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetCutoutMulti',
                request_serializer=orbit__pb2.GetCutoutMultiRequest.SerializeToString,
                response_deserializer=orbit__pb2.JsonBlob.FromString,
                _registered_method=True)
        self.GetSitePasses = channel.unary_unary(
                '/orbit.v1.OrbitScience/GetSitePasses',
                request_serializer=orbit__pb2.GetSitePassesRequest.SerializeToString,
                response_deserializer=orbit__pb2.GetSitePassesResponse.FromString,
                _registered_method=True)


class OrbitScienceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListSatellites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTLE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrbitInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolarCrossings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoverageHeatmap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFires(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimbadRegion(self, request, context):
        """Astronomy proxies (SIMBAD + HiPS cutouts) — JSON blob for Flask parity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimbadResolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSurveys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCutout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCutoutMulti(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSitePasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrbitScienceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSatellites': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSatellites,
                    request_deserializer=orbit__pb2.ListSatellitesRequest.FromString,
                    response_serializer=orbit__pb2.ListSatellitesResponse.SerializeToString,
            ),
            'GetTLE': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTLE,
                    request_deserializer=orbit__pb2.GetTLERequest.FromString,
                    response_serializer=orbit__pb2.GetTLEResponse.SerializeToString,
            ),
            'GetCurrentPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPosition,
                    request_deserializer=orbit__pb2.GetCurrentPositionRequest.FromString,
                    response_serializer=orbit__pb2.PositionResponse.SerializeToString,
            ),
            'GetTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrack,
                    request_deserializer=orbit__pb2.GetTrackRequest.FromString,
                    response_serializer=orbit__pb2.TrackResponse.SerializeToString,
            ),
            'GetOrbitInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrbitInfo,
                    request_deserializer=orbit__pb2.GetOrbitInfoRequest.FromString,
                    response_serializer=orbit__pb2.OrbitInfoResponse.SerializeToString,
            ),
            'GetSwath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwath,
                    request_deserializer=orbit__pb2.GetSwathRequest.FromString,
                    response_serializer=orbit__pb2.SwathResponse.SerializeToString,
            ),
            'GetPolarCrossings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolarCrossings,
                    request_deserializer=orbit__pb2.GetPolarCrossingsRequest.FromString,
                    response_serializer=orbit__pb2.PolarCrossingsResponse.SerializeToString,
            ),
            'GetCoverageHeatmap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoverageHeatmap,
                    request_deserializer=orbit__pb2.GetCoverageHeatmapRequest.FromString,
                    response_serializer=orbit__pb2.CoverageHeatmapResponse.SerializeToString,
            ),
            'GetFires': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFires,
                    request_deserializer=orbit__pb2.GetFiresRequest.FromString,
                    response_serializer=orbit__pb2.GetFiresResponse.SerializeToString,
            ),
            'SimbadRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.SimbadRegion,
                    request_deserializer=orbit__pb2.SimbadRegionRequest.FromString,
                    response_serializer=orbit__pb2.JsonBlob.SerializeToString,
            ),
            'SimbadResolve': grpc.unary_unary_rpc_method_handler(
                    servicer.SimbadResolve,
                    request_deserializer=orbit__pb2.SimbadResolveRequest.FromString,
                    response_serializer=orbit__pb2.JsonBlob.SerializeToString,
            ),
            'ListSurveys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSurveys,
                    request_deserializer=orbit__pb2.ListSurveysRequest.FromString,
                    response_serializer=orbit__pb2.JsonBlob.SerializeToString,
            ),
            'GetCutout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCutout,
                    request_deserializer=orbit__pb2.GetCutoutRequest.FromString,
                    response_serializer=orbit__pb2.JsonBlob.SerializeToString,
            ),
            'GetCutoutMulti': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCutoutMulti,
                    request_deserializer=orbit__pb2.GetCutoutMultiRequest.FromString,
                    response_serializer=orbit__pb2.JsonBlob.SerializeToString,
            ),
            'GetSitePasses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSitePasses,
                    request_deserializer=orbit__pb2.GetSitePassesRequest.FromString,
                    response_serializer=orbit__pb2.GetSitePassesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orbit.v1.OrbitScience', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orbit.v1.OrbitScience', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrbitScience:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSatellites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/ListSatellites',
            orbit__pb2.ListSatellitesRequest.SerializeToString,
            orbit__pb2.ListSatellitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTLE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetTLE',
            orbit__pb2.GetTLERequest.SerializeToString,
            orbit__pb2.GetTLEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetCurrentPosition',
            orbit__pb2.GetCurrentPositionRequest.SerializeToString,
            orbit__pb2.PositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetTrack',
            orbit__pb2.GetTrackRequest.SerializeToString,
            orbit__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrbitInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetOrbitInfo',
            orbit__pb2.GetOrbitInfoRequest.SerializeToString,
            orbit__pb2.OrbitInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSwath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetSwath',
            orbit__pb2.GetSwathRequest.SerializeToString,
            orbit__pb2.SwathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolarCrossings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetPolarCrossings',
            orbit__pb2.GetPolarCrossingsRequest.SerializeToString,
            orbit__pb2.PolarCrossingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoverageHeatmap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetCoverageHeatmap',
            orbit__pb2.GetCoverageHeatmapRequest.SerializeToString,
            orbit__pb2.CoverageHeatmapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFires(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetFires',
            orbit__pb2.GetFiresRequest.SerializeToString,
            orbit__pb2.GetFiresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimbadRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/SimbadRegion',
            orbit__pb2.SimbadRegionRequest.SerializeToString,
            orbit__pb2.JsonBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimbadResolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/SimbadResolve',
            orbit__pb2.SimbadResolveRequest.SerializeToString,
            orbit__pb2.JsonBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSurveys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/ListSurveys',
            orbit__pb2.ListSurveysRequest.SerializeToString,
            orbit__pb2.JsonBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCutout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetCutout',
            orbit__pb2.GetCutoutRequest.SerializeToString,
            orbit__pb2.JsonBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCutoutMulti(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetCutoutMulti',
            orbit__pb2.GetCutoutMultiRequest.SerializeToString,
            orbit__pb2.JsonBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSitePasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orbit.v1.OrbitScience/GetSitePasses',
            orbit__pb2.GetSitePassesRequest.SerializeToString,
            orbit__pb2.GetSitePassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
