// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: nightsky.proto

package nightskyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NightskyScience_Health_FullMethodName               = "/nightsky.v1.NightskyScience/Health"
	NightskyScience_Geocode_FullMethodName              = "/nightsky.v1.NightskyScience/Geocode"
	NightskyScience_Options_FullMethodName              = "/nightsky.v1.NightskyScience/Options"
	NightskyScience_Planets_FullMethodName              = "/nightsky.v1.NightskyScience/Planets"
	NightskyScience_Moon_FullMethodName                 = "/nightsky.v1.NightskyScience/Moon"
	NightskyScience_LocationInfo_FullMethodName         = "/nightsky.v1.NightskyScience/LocationInfo"
	NightskyScience_GeostationaryVisible_FullMethodName = "/nightsky.v1.NightskyScience/GeostationaryVisible"
	NightskyScience_GeostationaryArc_FullMethodName     = "/nightsky.v1.NightskyScience/GeostationaryArc"
	NightskyScience_GeostationaryLookup_FullMethodName  = "/nightsky.v1.NightskyScience/GeostationaryLookup"
	NightskyScience_GeostationaryList_FullMethodName    = "/nightsky.v1.NightskyScience/GeostationaryList"
	NightskyScience_Twilight_FullMethodName             = "/nightsky.v1.NightskyScience/Twilight"
	NightskyScience_RiseSet_FullMethodName              = "/nightsky.v1.NightskyScience/RiseSet"
	NightskyScience_Weather_FullMethodName              = "/nightsky.v1.NightskyScience/Weather"
	NightskyScience_GenerateSky_FullMethodName          = "/nightsky.v1.NightskyScience/GenerateSky"
	NightskyScience_AuroraKp_FullMethodName             = "/nightsky.v1.NightskyScience/AuroraKp"
	NightskyScience_LightPollution_FullMethodName       = "/nightsky.v1.NightskyScience/LightPollution"
	NightskyScience_SatelliteTLE_FullMethodName         = "/nightsky.v1.NightskyScience/SatelliteTLE"
	NightskyScience_Ephemeris_FullMethodName            = "/nightsky.v1.NightskyScience/Ephemeris"
	NightskyScience_SessionGoNoGo_FullMethodName        = "/nightsky.v1.NightskyScience/SessionGoNoGo"
)

// NightskyScienceClient is the client API for NightskyScience service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NightskyScience backs the Night Sky Viewer JSON API (port 5051 frontend).
// Complex Flask-shaped payloads travel as JSON strings so the Go edge can
// re-emit byte-identical response bodies without maintaining parallel schemas.
type NightskyScienceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	Options(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResponse, error)
	Planets(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	Moon(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	LocationInfo(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GeostationaryVisible(ctx context.Context, in *GeoVisibleRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GeostationaryArc(ctx context.Context, in *GeoArcRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GeostationaryLookup(ctx context.Context, in *GeoLookupRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GeostationaryList(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	Twilight(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	RiseSet(ctx context.Context, in *RiseSetRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	Weather(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GenerateSky(ctx context.Context, in *GenerateSkyRequest, opts ...grpc.CallOption) (*ImageResponse, error)
	AuroraKp(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	LightPollution(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	SatelliteTLE(ctx context.Context, in *SatelliteTLERequest, opts ...grpc.CallOption) (*JsonResponse, error)
	// Planner-facing aliases / session composition
	Ephemeris(ctx context.Context, in *EphemerisRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	SessionGoNoGo(ctx context.Context, in *SessionGoNoGoRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type nightskyScienceClient struct {
	cc grpc.ClientConnInterface
}

func NewNightskyScienceClient(cc grpc.ClientConnInterface) NightskyScienceClient {
	return &nightskyScienceClient{cc}
}

func (c *nightskyScienceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Geocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Options(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Options_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Planets(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Planets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Moon(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Moon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) LocationInfo(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_LocationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) GeostationaryVisible(ctx context.Context, in *GeoVisibleRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_GeostationaryVisible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) GeostationaryArc(ctx context.Context, in *GeoArcRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_GeostationaryArc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) GeostationaryLookup(ctx context.Context, in *GeoLookupRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_GeostationaryLookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) GeostationaryList(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_GeostationaryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Twilight(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Twilight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) RiseSet(ctx context.Context, in *RiseSetRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_RiseSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Weather(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Weather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) GenerateSky(ctx context.Context, in *GenerateSkyRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, NightskyScience_GenerateSky_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) AuroraKp(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_AuroraKp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) LightPollution(ctx context.Context, in *LatLonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_LightPollution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) SatelliteTLE(ctx context.Context, in *SatelliteTLERequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_SatelliteTLE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) Ephemeris(ctx context.Context, in *EphemerisRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_Ephemeris_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nightskyScienceClient) SessionGoNoGo(ctx context.Context, in *SessionGoNoGoRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, NightskyScience_SessionGoNoGo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NightskyScienceServer is the server API for NightskyScience service.
// All implementations must embed UnimplementedNightskyScienceServer
// for forward compatibility.
//
// NightskyScience backs the Night Sky Viewer JSON API (port 5051 frontend).
// Complex Flask-shaped payloads travel as JSON strings so the Go edge can
// re-emit byte-identical response bodies without maintaining parallel schemas.
type NightskyScienceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Geocode(context.Context, *GeocodeRequest) (*JsonResponse, error)
	Options(context.Context, *Empty) (*JsonResponse, error)
	Planets(context.Context, *LatLonRequest) (*JsonResponse, error)
	Moon(context.Context, *LatLonRequest) (*JsonResponse, error)
	LocationInfo(context.Context, *LatLonRequest) (*JsonResponse, error)
	GeostationaryVisible(context.Context, *GeoVisibleRequest) (*JsonResponse, error)
	GeostationaryArc(context.Context, *GeoArcRequest) (*JsonResponse, error)
	GeostationaryLookup(context.Context, *GeoLookupRequest) (*JsonResponse, error)
	GeostationaryList(context.Context, *CategoryRequest) (*JsonResponse, error)
	Twilight(context.Context, *LatLonRequest) (*JsonResponse, error)
	RiseSet(context.Context, *RiseSetRequest) (*JsonResponse, error)
	Weather(context.Context, *LatLonRequest) (*JsonResponse, error)
	GenerateSky(context.Context, *GenerateSkyRequest) (*ImageResponse, error)
	AuroraKp(context.Context, *LatLonRequest) (*JsonResponse, error)
	LightPollution(context.Context, *LatLonRequest) (*JsonResponse, error)
	SatelliteTLE(context.Context, *SatelliteTLERequest) (*JsonResponse, error)
	// Planner-facing aliases / session composition
	Ephemeris(context.Context, *EphemerisRequest) (*JsonResponse, error)
	SessionGoNoGo(context.Context, *SessionGoNoGoRequest) (*JsonResponse, error)
	mustEmbedUnimplementedNightskyScienceServer()
}

// UnimplementedNightskyScienceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNightskyScienceServer struct{}

func (UnimplementedNightskyScienceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNightskyScienceServer) Geocode(context.Context, *GeocodeRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedNightskyScienceServer) Options(context.Context, *Empty) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Options not implemented")
}
func (UnimplementedNightskyScienceServer) Planets(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Planets not implemented")
}
func (UnimplementedNightskyScienceServer) Moon(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Moon not implemented")
}
func (UnimplementedNightskyScienceServer) LocationInfo(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LocationInfo not implemented")
}
func (UnimplementedNightskyScienceServer) GeostationaryVisible(context.Context, *GeoVisibleRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeostationaryVisible not implemented")
}
func (UnimplementedNightskyScienceServer) GeostationaryArc(context.Context, *GeoArcRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeostationaryArc not implemented")
}
func (UnimplementedNightskyScienceServer) GeostationaryLookup(context.Context, *GeoLookupRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeostationaryLookup not implemented")
}
func (UnimplementedNightskyScienceServer) GeostationaryList(context.Context, *CategoryRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeostationaryList not implemented")
}
func (UnimplementedNightskyScienceServer) Twilight(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Twilight not implemented")
}
func (UnimplementedNightskyScienceServer) RiseSet(context.Context, *RiseSetRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RiseSet not implemented")
}
func (UnimplementedNightskyScienceServer) Weather(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Weather not implemented")
}
func (UnimplementedNightskyScienceServer) GenerateSky(context.Context, *GenerateSkyRequest) (*ImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSky not implemented")
}
func (UnimplementedNightskyScienceServer) AuroraKp(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuroraKp not implemented")
}
func (UnimplementedNightskyScienceServer) LightPollution(context.Context, *LatLonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LightPollution not implemented")
}
func (UnimplementedNightskyScienceServer) SatelliteTLE(context.Context, *SatelliteTLERequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SatelliteTLE not implemented")
}
func (UnimplementedNightskyScienceServer) Ephemeris(context.Context, *EphemerisRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ephemeris not implemented")
}
func (UnimplementedNightskyScienceServer) SessionGoNoGo(context.Context, *SessionGoNoGoRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionGoNoGo not implemented")
}
func (UnimplementedNightskyScienceServer) mustEmbedUnimplementedNightskyScienceServer() {}
func (UnimplementedNightskyScienceServer) testEmbeddedByValue()                         {}

// UnsafeNightskyScienceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NightskyScienceServer will
// result in compilation errors.
type UnsafeNightskyScienceServer interface {
	mustEmbedUnimplementedNightskyScienceServer()
}

func RegisterNightskyScienceServer(s grpc.ServiceRegistrar, srv NightskyScienceServer) {
	// If the following call panics, it indicates UnimplementedNightskyScienceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NightskyScience_ServiceDesc, srv)
}

func _NightskyScience_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Geocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Options_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Options(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Planets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Planets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Planets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Planets(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Moon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Moon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Moon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Moon(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_LocationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).LocationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_LocationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).LocationInfo(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_GeostationaryVisible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoVisibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).GeostationaryVisible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_GeostationaryVisible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).GeostationaryVisible(ctx, req.(*GeoVisibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_GeostationaryArc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoArcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).GeostationaryArc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_GeostationaryArc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).GeostationaryArc(ctx, req.(*GeoArcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_GeostationaryLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).GeostationaryLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_GeostationaryLookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).GeostationaryLookup(ctx, req.(*GeoLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_GeostationaryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).GeostationaryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_GeostationaryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).GeostationaryList(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Twilight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Twilight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Twilight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Twilight(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_RiseSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiseSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).RiseSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_RiseSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).RiseSet(ctx, req.(*RiseSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Weather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Weather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Weather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Weather(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_GenerateSky_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSkyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).GenerateSky(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_GenerateSky_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).GenerateSky(ctx, req.(*GenerateSkyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_AuroraKp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).AuroraKp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_AuroraKp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).AuroraKp(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_LightPollution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).LightPollution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_LightPollution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).LightPollution(ctx, req.(*LatLonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_SatelliteTLE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatelliteTLERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).SatelliteTLE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_SatelliteTLE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).SatelliteTLE(ctx, req.(*SatelliteTLERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_Ephemeris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EphemerisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).Ephemeris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_Ephemeris_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).Ephemeris(ctx, req.(*EphemerisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NightskyScience_SessionGoNoGo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGoNoGoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NightskyScienceServer).SessionGoNoGo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NightskyScience_SessionGoNoGo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NightskyScienceServer).SessionGoNoGo(ctx, req.(*SessionGoNoGoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NightskyScience_ServiceDesc is the grpc.ServiceDesc for NightskyScience service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NightskyScience_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nightsky.v1.NightskyScience",
	HandlerType: (*NightskyScienceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _NightskyScience_Health_Handler,
		},
		{
			MethodName: "Geocode",
			Handler:    _NightskyScience_Geocode_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _NightskyScience_Options_Handler,
		},
		{
			MethodName: "Planets",
			Handler:    _NightskyScience_Planets_Handler,
		},
		{
			MethodName: "Moon",
			Handler:    _NightskyScience_Moon_Handler,
		},
		{
			MethodName: "LocationInfo",
			Handler:    _NightskyScience_LocationInfo_Handler,
		},
		{
			MethodName: "GeostationaryVisible",
			Handler:    _NightskyScience_GeostationaryVisible_Handler,
		},
		{
			MethodName: "GeostationaryArc",
			Handler:    _NightskyScience_GeostationaryArc_Handler,
		},
		{
			MethodName: "GeostationaryLookup",
			Handler:    _NightskyScience_GeostationaryLookup_Handler,
		},
		{
			MethodName: "GeostationaryList",
			Handler:    _NightskyScience_GeostationaryList_Handler,
		},
		{
			MethodName: "Twilight",
			Handler:    _NightskyScience_Twilight_Handler,
		},
		{
			MethodName: "RiseSet",
			Handler:    _NightskyScience_RiseSet_Handler,
		},
		{
			MethodName: "Weather",
			Handler:    _NightskyScience_Weather_Handler,
		},
		{
			MethodName: "GenerateSky",
			Handler:    _NightskyScience_GenerateSky_Handler,
		},
		{
			MethodName: "AuroraKp",
			Handler:    _NightskyScience_AuroraKp_Handler,
		},
		{
			MethodName: "LightPollution",
			Handler:    _NightskyScience_LightPollution_Handler,
		},
		{
			MethodName: "SatelliteTLE",
			Handler:    _NightskyScience_SatelliteTLE_Handler,
		},
		{
			MethodName: "Ephemeris",
			Handler:    _NightskyScience_Ephemeris_Handler,
		},
		{
			MethodName: "SessionGoNoGo",
			Handler:    _NightskyScience_SessionGoNoGo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nightsky.proto",
}
