// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nightsky.proto

package nightskyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_nightsky_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_nightsky_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_nightsky_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Flask-compatible JSON blob for the HTTP edge to write as the response body.
type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`                                // JSON object/array text (empty if hard failure)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                              // optional machine-readable error
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status to emit (200, 400, 404, 502, …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_nightsky_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{3}
}

func (x *JsonResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *JsonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JsonResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type LatLonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLonRequest) Reset() {
	*x = LatLonRequest{}
	mi := &file_nightsky_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLonRequest) ProtoMessage() {}

func (x *LatLonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLonRequest.ProtoReflect.Descriptor instead.
func (*LatLonRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{4}
}

func (x *LatLonRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLonRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_nightsky_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{5}
}

func (x *GeocodeRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type GeoVisibleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	MinElevation  float64                `protobuf:"fixed64,4,opt,name=min_elevation,json=minElevation,proto3" json:"min_elevation,omitempty"` // default 5 if 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoVisibleRequest) Reset() {
	*x = GeoVisibleRequest{}
	mi := &file_nightsky_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoVisibleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoVisibleRequest) ProtoMessage() {}

func (x *GeoVisibleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoVisibleRequest.ProtoReflect.Descriptor instead.
func (*GeoVisibleRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{6}
}

func (x *GeoVisibleRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoVisibleRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoVisibleRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GeoVisibleRequest) GetMinElevation() float64 {
	if x != nil {
		return x.MinElevation
	}
	return 0
}

type GeoArcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Points        int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"` // default 72 if 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoArcRequest) Reset() {
	*x = GeoArcRequest{}
	mi := &file_nightsky_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoArcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoArcRequest) ProtoMessage() {}

func (x *GeoArcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoArcRequest.ProtoReflect.Descriptor instead.
func (*GeoArcRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{7}
}

func (x *GeoArcRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoArcRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoArcRequest) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type GeoLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	SatLon        float64                `protobuf:"fixed64,3,opt,name=sat_lon,json=satLon,proto3" json:"sat_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLookupRequest) Reset() {
	*x = GeoLookupRequest{}
	mi := &file_nightsky_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLookupRequest) ProtoMessage() {}

func (x *GeoLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLookupRequest.ProtoReflect.Descriptor instead.
func (*GeoLookupRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{8}
}

func (x *GeoLookupRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoLookupRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoLookupRequest) GetSatLon() float64 {
	if x != nil {
		return x.SatLon
	}
	return 0
}

type CategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_nightsky_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type RiseSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"` // sun, moon, mars, …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiseSetRequest) Reset() {
	*x = RiseSetRequest{}
	mi := &file_nightsky_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiseSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiseSetRequest) ProtoMessage() {}

func (x *RiseSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiseSetRequest.ProtoReflect.Descriptor instead.
func (*RiseSetRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{10}
}

func (x *RiseSetRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RiseSetRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RiseSetRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type SatelliteTLERequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	NoradId       string                 `protobuf:"bytes,2,opt,name=norad_id,json=noradId,proto3" json:"norad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteTLERequest) Reset() {
	*x = SatelliteTLERequest{}
	mi := &file_nightsky_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteTLERequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteTLERequest) ProtoMessage() {}

func (x *SatelliteTLERequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteTLERequest.ProtoReflect.Descriptor instead.
func (*SatelliteTLERequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{11}
}

func (x *SatelliteTLERequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SatelliteTLERequest) GetNoradId() string {
	if x != nil {
		return x.NoradId
	}
	return ""
}

type GenerateSkyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw JSON body matching POST /api/nightsky/generate
	RequestJson   string `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSkyRequest) Reset() {
	*x = GenerateSkyRequest{}
	mi := &file_nightsky_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSkyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSkyRequest) ProtoMessage() {}

func (x *GenerateSkyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSkyRequest.ProtoReflect.Descriptor instead.
func (*GenerateSkyRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateSkyRequest) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/png, image/jpeg, image/svg+xml
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_nightsky_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{13}
}

func (x *ImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ImageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ImageResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type EphemerisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // object name: mars, moon, M31, etc.
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EphemerisRequest) Reset() {
	*x = EphemerisRequest{}
	mi := &file_nightsky_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EphemerisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemerisRequest) ProtoMessage() {}

func (x *EphemerisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemerisRequest.ProtoReflect.Descriptor instead.
func (*EphemerisRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{14}
}

func (x *EphemerisRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EphemerisRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *EphemerisRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type SessionGoNoGoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGoNoGoRequest) Reset() {
	*x = SessionGoNoGoRequest{}
	mi := &file_nightsky_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGoNoGoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGoNoGoRequest) ProtoMessage() {}

func (x *SessionGoNoGoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightsky_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGoNoGoRequest.ProtoReflect.Descriptor instead.
func (*SessionGoNoGoRequest) Descriptor() ([]byte, []int) {
	return file_nightsky_proto_rawDescGZIP(), []int{15}
}

func (x *SessionGoNoGoRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SessionGoNoGoRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

var File_nightsky_proto protoreflect.FileDescriptor

const file_nightsky_proto_rawDesc = "" +
	"\n" +
	"\x0enightsky.proto\x12\vnightsky.v1\"\a\n" +
	"\x05Empty\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"3\n" +
	"\rLatLonRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\x1e\n" +
	"\x0eGeocodeRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"x\n" +
	"\x11GeoVisibleRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12#\n" +
	"\rmin_elevation\x18\x04 \x01(\x01R\fminElevation\"K\n" +
	"\rGeoArcRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\"O\n" +
	"\x10GeoLookupRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x17\n" +
	"\asat_lon\x18\x03 \x01(\x01R\x06satLon\"-\n" +
	"\x0fCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"L\n" +
	"\x0eRiseSetRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"F\n" +
	"\x13SatelliteTLERequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x19\n" +
	"\bnorad_id\x18\x02 \x01(\tR\anoradId\"7\n" +
	"\x12GenerateSkyRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\tR\vrequestJson\"}\n" +
	"\rImageResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\"J\n" +
	"\x10EphemerisRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\":\n" +
	"\x14SessionGoNoGoRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon2\xd9\n" +
	"\n" +
	"\x0fNightskyScience\x12A\n" +
	"\x06Health\x12\x1a.nightsky.v1.HealthRequest\x1a\x1b.nightsky.v1.HealthResponse\x12A\n" +
	"\aGeocode\x12\x1b.nightsky.v1.GeocodeRequest\x1a\x19.nightsky.v1.JsonResponse\x128\n" +
	"\aOptions\x12\x12.nightsky.v1.Empty\x1a\x19.nightsky.v1.JsonResponse\x12@\n" +
	"\aPlanets\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12=\n" +
	"\x04Moon\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12E\n" +
	"\fLocationInfo\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12Q\n" +
	"\x14GeostationaryVisible\x12\x1e.nightsky.v1.GeoVisibleRequest\x1a\x19.nightsky.v1.JsonResponse\x12I\n" +
	"\x10GeostationaryArc\x12\x1a.nightsky.v1.GeoArcRequest\x1a\x19.nightsky.v1.JsonResponse\x12O\n" +
	"\x13GeostationaryLookup\x12\x1d.nightsky.v1.GeoLookupRequest\x1a\x19.nightsky.v1.JsonResponse\x12L\n" +
	"\x11GeostationaryList\x12\x1c.nightsky.v1.CategoryRequest\x1a\x19.nightsky.v1.JsonResponse\x12A\n" +
	"\bTwilight\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12A\n" +
	"\aRiseSet\x12\x1b.nightsky.v1.RiseSetRequest\x1a\x19.nightsky.v1.JsonResponse\x12@\n" +
	"\aWeather\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12J\n" +
	"\vGenerateSky\x12\x1f.nightsky.v1.GenerateSkyRequest\x1a\x1a.nightsky.v1.ImageResponse\x12A\n" +
	"\bAuroraKp\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12G\n" +
	"\x0eLightPollution\x12\x1a.nightsky.v1.LatLonRequest\x1a\x19.nightsky.v1.JsonResponse\x12K\n" +
	"\fSatelliteTLE\x12 .nightsky.v1.SatelliteTLERequest\x1a\x19.nightsky.v1.JsonResponse\x12E\n" +
	"\tEphemeris\x12\x1d.nightsky.v1.EphemerisRequest\x1a\x19.nightsky.v1.JsonResponse\x12M\n" +
	"\rSessionGoNoGo\x12!.nightsky.v1.SessionGoNoGoRequest\x1a\x19.nightsky.v1.JsonResponseB/Z-noaa21_orbit/api/proto/nightsky/v1;nightskyv1b\x06proto3"

var (
	file_nightsky_proto_rawDescOnce sync.Once
	file_nightsky_proto_rawDescData []byte
)

func file_nightsky_proto_rawDescGZIP() []byte {
	file_nightsky_proto_rawDescOnce.Do(func() {
		file_nightsky_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nightsky_proto_rawDesc), len(file_nightsky_proto_rawDesc)))
	})
	return file_nightsky_proto_rawDescData
}

var file_nightsky_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_nightsky_proto_goTypes = []any{
	(*Empty)(nil),                // 0: nightsky.v1.Empty
	(*HealthRequest)(nil),        // 1: nightsky.v1.HealthRequest
	(*HealthResponse)(nil),       // 2: nightsky.v1.HealthResponse
	(*JsonResponse)(nil),         // 3: nightsky.v1.JsonResponse
	(*LatLonRequest)(nil),        // 4: nightsky.v1.LatLonRequest
	(*GeocodeRequest)(nil),       // 5: nightsky.v1.GeocodeRequest
	(*GeoVisibleRequest)(nil),    // 6: nightsky.v1.GeoVisibleRequest
	(*GeoArcRequest)(nil),        // 7: nightsky.v1.GeoArcRequest
	(*GeoLookupRequest)(nil),     // 8: nightsky.v1.GeoLookupRequest
	(*CategoryRequest)(nil),      // 9: nightsky.v1.CategoryRequest
	(*RiseSetRequest)(nil),       // 10: nightsky.v1.RiseSetRequest
	(*SatelliteTLERequest)(nil),  // 11: nightsky.v1.SatelliteTLERequest
	(*GenerateSkyRequest)(nil),   // 12: nightsky.v1.GenerateSkyRequest
	(*ImageResponse)(nil),        // 13: nightsky.v1.ImageResponse
	(*EphemerisRequest)(nil),     // 14: nightsky.v1.EphemerisRequest
	(*SessionGoNoGoRequest)(nil), // 15: nightsky.v1.SessionGoNoGoRequest
}
var file_nightsky_proto_depIdxs = []int32{
	1,  // 0: nightsky.v1.NightskyScience.Health:input_type -> nightsky.v1.HealthRequest
	5,  // 1: nightsky.v1.NightskyScience.Geocode:input_type -> nightsky.v1.GeocodeRequest
	0,  // 2: nightsky.v1.NightskyScience.Options:input_type -> nightsky.v1.Empty
	4,  // 3: nightsky.v1.NightskyScience.Planets:input_type -> nightsky.v1.LatLonRequest
	4,  // 4: nightsky.v1.NightskyScience.Moon:input_type -> nightsky.v1.LatLonRequest
	4,  // 5: nightsky.v1.NightskyScience.LocationInfo:input_type -> nightsky.v1.LatLonRequest
	6,  // 6: nightsky.v1.NightskyScience.GeostationaryVisible:input_type -> nightsky.v1.GeoVisibleRequest
	7,  // 7: nightsky.v1.NightskyScience.GeostationaryArc:input_type -> nightsky.v1.GeoArcRequest
	8,  // 8: nightsky.v1.NightskyScience.GeostationaryLookup:input_type -> nightsky.v1.GeoLookupRequest
	9,  // 9: nightsky.v1.NightskyScience.GeostationaryList:input_type -> nightsky.v1.CategoryRequest
	4,  // 10: nightsky.v1.NightskyScience.Twilight:input_type -> nightsky.v1.LatLonRequest
	10, // 11: nightsky.v1.NightskyScience.RiseSet:input_type -> nightsky.v1.RiseSetRequest
	4,  // 12: nightsky.v1.NightskyScience.Weather:input_type -> nightsky.v1.LatLonRequest
	12, // 13: nightsky.v1.NightskyScience.GenerateSky:input_type -> nightsky.v1.GenerateSkyRequest
	4,  // 14: nightsky.v1.NightskyScience.AuroraKp:input_type -> nightsky.v1.LatLonRequest
	4,  // 15: nightsky.v1.NightskyScience.LightPollution:input_type -> nightsky.v1.LatLonRequest
	11, // 16: nightsky.v1.NightskyScience.SatelliteTLE:input_type -> nightsky.v1.SatelliteTLERequest
	14, // 17: nightsky.v1.NightskyScience.Ephemeris:input_type -> nightsky.v1.EphemerisRequest
	15, // 18: nightsky.v1.NightskyScience.SessionGoNoGo:input_type -> nightsky.v1.SessionGoNoGoRequest
	2,  // 19: nightsky.v1.NightskyScience.Health:output_type -> nightsky.v1.HealthResponse
	3,  // 20: nightsky.v1.NightskyScience.Geocode:output_type -> nightsky.v1.JsonResponse
	3,  // 21: nightsky.v1.NightskyScience.Options:output_type -> nightsky.v1.JsonResponse
	3,  // 22: nightsky.v1.NightskyScience.Planets:output_type -> nightsky.v1.JsonResponse
	3,  // 23: nightsky.v1.NightskyScience.Moon:output_type -> nightsky.v1.JsonResponse
	3,  // 24: nightsky.v1.NightskyScience.LocationInfo:output_type -> nightsky.v1.JsonResponse
	3,  // 25: nightsky.v1.NightskyScience.GeostationaryVisible:output_type -> nightsky.v1.JsonResponse
	3,  // 26: nightsky.v1.NightskyScience.GeostationaryArc:output_type -> nightsky.v1.JsonResponse
	3,  // 27: nightsky.v1.NightskyScience.GeostationaryLookup:output_type -> nightsky.v1.JsonResponse
	3,  // 28: nightsky.v1.NightskyScience.GeostationaryList:output_type -> nightsky.v1.JsonResponse
	3,  // 29: nightsky.v1.NightskyScience.Twilight:output_type -> nightsky.v1.JsonResponse
	3,  // 30: nightsky.v1.NightskyScience.RiseSet:output_type -> nightsky.v1.JsonResponse
	3,  // 31: nightsky.v1.NightskyScience.Weather:output_type -> nightsky.v1.JsonResponse
	13, // 32: nightsky.v1.NightskyScience.GenerateSky:output_type -> nightsky.v1.ImageResponse
	3,  // 33: nightsky.v1.NightskyScience.AuroraKp:output_type -> nightsky.v1.JsonResponse
	3,  // 34: nightsky.v1.NightskyScience.LightPollution:output_type -> nightsky.v1.JsonResponse
	3,  // 35: nightsky.v1.NightskyScience.SatelliteTLE:output_type -> nightsky.v1.JsonResponse
	3,  // 36: nightsky.v1.NightskyScience.Ephemeris:output_type -> nightsky.v1.JsonResponse
	3,  // 37: nightsky.v1.NightskyScience.SessionGoNoGo:output_type -> nightsky.v1.JsonResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_nightsky_proto_init() }
func file_nightsky_proto_init() {
	if File_nightsky_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nightsky_proto_rawDesc), len(file_nightsky_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nightsky_proto_goTypes,
		DependencyIndexes: file_nightsky_proto_depIdxs,
		MessageInfos:      file_nightsky_proto_msgTypes,
	}.Build()
	File_nightsky_proto = out.File
	file_nightsky_proto_goTypes = nil
	file_nightsky_proto_depIdxs = nil
}
