# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from backend.nightsky_science import nightsky_pb2 as nightsky__pb2
except ImportError:
    import nightsky_pb2 as nightsky__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nightsky_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NightskyScienceStub:
    """NightskyScience backs the Night Sky Viewer JSON API (port 5051 frontend).
    Complex Flask-shaped payloads travel as JSON strings so the Go edge can
    re-emit byte-identical response bodies without maintaining parallel schemas.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Health',
                request_serializer=nightsky__pb2.HealthRequest.SerializeToString,
                response_deserializer=nightsky__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Geocode = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Geocode',
                request_serializer=nightsky__pb2.GeocodeRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Options = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Options',
                request_serializer=nightsky__pb2.Empty.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Planets = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Planets',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Moon = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Moon',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.LocationInfo = channel.unary_unary(
                '/nightsky.v1.NightskyScience/LocationInfo',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GeostationaryVisible = channel.unary_unary(
                '/nightsky.v1.NightskyScience/GeostationaryVisible',
                request_serializer=nightsky__pb2.GeoVisibleRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GeostationaryArc = channel.unary_unary(
                '/nightsky.v1.NightskyScience/GeostationaryArc',
                request_serializer=nightsky__pb2.GeoArcRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GeostationaryLookup = channel.unary_unary(
                '/nightsky.v1.NightskyScience/GeostationaryLookup',
                request_serializer=nightsky__pb2.GeoLookupRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GeostationaryList = channel.unary_unary(
                '/nightsky.v1.NightskyScience/GeostationaryList',
                request_serializer=nightsky__pb2.CategoryRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Twilight = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Twilight',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.RiseSet = channel.unary_unary(
                '/nightsky.v1.NightskyScience/RiseSet',
                request_serializer=nightsky__pb2.RiseSetRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Weather = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Weather',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GenerateSky = channel.unary_unary(
                '/nightsky.v1.NightskyScience/GenerateSky',
                request_serializer=nightsky__pb2.GenerateSkyRequest.SerializeToString,
                response_deserializer=nightsky__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.AuroraKp = channel.unary_unary(
                '/nightsky.v1.NightskyScience/AuroraKp',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.LightPollution = channel.unary_unary(
                '/nightsky.v1.NightskyScience/LightPollution',
                request_serializer=nightsky__pb2.LatLonRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.SatelliteTLE = channel.unary_unary(
                '/nightsky.v1.NightskyScience/SatelliteTLE',
                request_serializer=nightsky__pb2.SatelliteTLERequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Ephemeris = channel.unary_unary(
                '/nightsky.v1.NightskyScience/Ephemeris',
                request_serializer=nightsky__pb2.EphemerisRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.SessionGoNoGo = channel.unary_unary(
                '/nightsky.v1.NightskyScience/SessionGoNoGo',
                request_serializer=nightsky__pb2.SessionGoNoGoRequest.SerializeToString,
                response_deserializer=nightsky__pb2.JsonResponse.FromString,
                _registered_method=True)


class NightskyScienceServicer:
    """NightskyScience backs the Night Sky Viewer JSON API (port 5051 frontend).
    Complex Flask-shaped payloads travel as JSON strings so the Go edge can
    re-emit byte-identical response bodies without maintaining parallel schemas.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Geocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Options(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Planets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocationInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeostationaryVisible(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeostationaryArc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeostationaryLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeostationaryList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Twilight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RiseSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Weather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSky(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuroraKp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LightPollution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SatelliteTLE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ephemeris(self, request, context):
        """Planner-facing aliases / session composition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionGoNoGo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NightskyScienceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=nightsky__pb2.HealthRequest.FromString,
                    response_serializer=nightsky__pb2.HealthResponse.SerializeToString,
            ),
            'Geocode': grpc.unary_unary_rpc_method_handler(
                    servicer.Geocode,
                    request_deserializer=nightsky__pb2.GeocodeRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Options': grpc.unary_unary_rpc_method_handler(
                    servicer.Options,
                    request_deserializer=nightsky__pb2.Empty.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Planets': grpc.unary_unary_rpc_method_handler(
                    servicer.Planets,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Moon': grpc.unary_unary_rpc_method_handler(
                    servicer.Moon,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'LocationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.LocationInfo,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'GeostationaryVisible': grpc.unary_unary_rpc_method_handler(
                    servicer.GeostationaryVisible,
                    request_deserializer=nightsky__pb2.GeoVisibleRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'GeostationaryArc': grpc.unary_unary_rpc_method_handler(
                    servicer.GeostationaryArc,
                    request_deserializer=nightsky__pb2.GeoArcRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'GeostationaryLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.GeostationaryLookup,
                    request_deserializer=nightsky__pb2.GeoLookupRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'GeostationaryList': grpc.unary_unary_rpc_method_handler(
                    servicer.GeostationaryList,
                    request_deserializer=nightsky__pb2.CategoryRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Twilight': grpc.unary_unary_rpc_method_handler(
                    servicer.Twilight,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'RiseSet': grpc.unary_unary_rpc_method_handler(
                    servicer.RiseSet,
                    request_deserializer=nightsky__pb2.RiseSetRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Weather': grpc.unary_unary_rpc_method_handler(
                    servicer.Weather,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'GenerateSky': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSky,
                    request_deserializer=nightsky__pb2.GenerateSkyRequest.FromString,
                    response_serializer=nightsky__pb2.ImageResponse.SerializeToString,
            ),
            'AuroraKp': grpc.unary_unary_rpc_method_handler(
                    servicer.AuroraKp,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'LightPollution': grpc.unary_unary_rpc_method_handler(
                    servicer.LightPollution,
                    request_deserializer=nightsky__pb2.LatLonRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'SatelliteTLE': grpc.unary_unary_rpc_method_handler(
                    servicer.SatelliteTLE,
                    request_deserializer=nightsky__pb2.SatelliteTLERequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'Ephemeris': grpc.unary_unary_rpc_method_handler(
                    servicer.Ephemeris,
                    request_deserializer=nightsky__pb2.EphemerisRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
            'SessionGoNoGo': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionGoNoGo,
                    request_deserializer=nightsky__pb2.SessionGoNoGoRequest.FromString,
                    response_serializer=nightsky__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nightsky.v1.NightskyScience', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nightsky.v1.NightskyScience', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NightskyScience:
    """NightskyScience backs the Night Sky Viewer JSON API (port 5051 frontend).
    Complex Flask-shaped payloads travel as JSON strings so the Go edge can
    re-emit byte-identical response bodies without maintaining parallel schemas.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Health',
            nightsky__pb2.HealthRequest.SerializeToString,
            nightsky__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Geocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Geocode',
            nightsky__pb2.GeocodeRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Options(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Options',
            nightsky__pb2.Empty.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Planets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Planets',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Moon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Moon',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/LocationInfo',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeostationaryVisible(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/GeostationaryVisible',
            nightsky__pb2.GeoVisibleRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeostationaryArc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/GeostationaryArc',
            nightsky__pb2.GeoArcRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeostationaryLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/GeostationaryLookup',
            nightsky__pb2.GeoLookupRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeostationaryList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/GeostationaryList',
            nightsky__pb2.CategoryRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Twilight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Twilight',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RiseSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/RiseSet',
            nightsky__pb2.RiseSetRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Weather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Weather',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSky(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/GenerateSky',
            nightsky__pb2.GenerateSkyRequest.SerializeToString,
            nightsky__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuroraKp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/AuroraKp',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LightPollution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/LightPollution',
            nightsky__pb2.LatLonRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SatelliteTLE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/SatelliteTLE',
            nightsky__pb2.SatelliteTLERequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ephemeris(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/Ephemeris',
            nightsky__pb2.EphemerisRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionGoNoGo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nightsky.v1.NightskyScience/SessionGoNoGo',
            nightsky__pb2.SessionGoNoGoRequest.SerializeToString,
            nightsky__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
